### ISSUE TITLE
Add/remove new possible choices after a call to add_set 

### ISSUE THREAD

**Issue by kouchy** [CLIUtils/CLI11#113]
Hi CLI11 team,

Great job with this library, I really enjoy the simplicity !

I'm trying to use CLI11 in [AFF3CT](https://github.com/aff3ct/aff3ct), here is a code example:
```cpp
CLI::App app{"App description"};

std::string type;
auto opt = app.add_set("--type", type, {"TYPE1","TYPE2","TYPE3","TYPE4","TYPE5"}, "A type");

// I would like to do something like this to add a choice
opt->add_choices({"TYPE6", "TYPE7"});

// and something like this to remove a choice
opt->remove_choices({"TYPE1", "TYPE2"});
```

Is it possible to do something like this with CLI11?
If not, should it be possible to add this type of feature ?

Many thanks,
Adrien

**Comment by henryiii** [comment]
In the long run, a nicer set-like wrapper might be something worth investigating for someone. But for now, the lack of a way to pass a reference was an oversight. (Fixed in PR, waiting to make sure older compilers are okay with L vs. R value selection)

**Comment by henryiii** [comment]
Let me know if that didn't fix it!

**Comment by kouchy** [comment]
Hi Henry,

I pulled the last commits from the master and it does not seem to work.

Here is my code:
```cpp
std::string sim_type = "BFER";
std::set<std::string> sim_type_items = {"BFER", "BFERI"};
app.add_set(
	"--type",
	sim_type,
	sim_type_items,
	"Select the type of simulation to launch",
	true)
	->group("Standard");
sim_type_items.insert("EXIT");
```
The help displays:
```
 --type TEXT in {BFER,BFERI}=BFER
                              Select the type of simulation to launch
```
When it should display:
```
 --type TEXT in {BFER,BFERI,EXIT}=BFER
                              Select the type of simulation to launch
```
Any ideas? Perhaps I'm doing something wrong?

**Comment by henryiii** [comment]
Oops, yes, the help text will not update, since it is created at creation time. The behavior will update, but not the help text. I'll have to think about that.

**Comment by kouchy** [comment]
Ok cool and thanks :-). An other thing, I would prefer to have a getter to get the set than to have to keep the set by myself.

Now we have:
```cpp
std::string sim_type = "BFER";
std::set<std::string> sim_type_items = {"BFER", "BFERI"};
app.add_set(
	"--type",
	sim_type,
	sim_type_items,
	"Select the type of simulation to launch",
	true)
	->group("Standard");
sim_type_items.insert("EXIT");
```
To my mind it could be nice to have:
```cpp
std::string sim_type = "BFER";
auto *opt = app.add_set(
	"--type",
	sim_type,
	{"BFER", "BFERI"},
	"Select the type of simulation to launch",
	true)
	->group("Standard");
auto& set = opt->get_set();
set.insert("EXIT");
```
What do you think?

**Comment by henryiii** [comment]
For now, you can manually update the type value with:

```cpp
Option* opt = app.add_set(...
...
std::string typeval = detail::type_name< std::string >();
typeval += " in {" + detail::join(sim_type_items) + "}";
opt->set_type_name(typeval);
```

I might have an idea that would work for updating the text automagically.

**Comment by henryiii** [comment]
For now, that's how CLI11 works. You also have to create `sim_type` and keep it yourself; this is consistent. Right now, CLI11 is designed in terms of lambda functions instead of using inheritance. There is no way to `get_value` because Option doesn't know what it's holding; it's all done by lambda capture. `Option` for a set is not any different than `Option` for a flag or other option.

At some point, `Option`'s might become `Option<T>` (and `Flag`, `Set<T>`, etc), in which case something like `get_set` could be added. However, it might be that the simple flexibility of CLI11 would be lost with such a redesign, so it might not happen.

**Comment by kouchy** [comment]
Ok fair enough, I can live with that and I agree this is consistent.

**Comment by kouchy** [comment]
I plan to use the "Formatting help output" feature of CLI11 in the future. In that case, I think that the proposed hack is not fully adapted. Am I right?

I am referring to this hack:
```cpp
Option* opt = app.add_set(...
...
std::string typeval = detail::type_name< std::string >();
typeval += " in {" + detail::join(sim_type_items) + "}";
opt->set_type_name(typeval);
```

**Comment by henryiii** [comment]
For the Formatter, the type name of a set option is `T in { VALUE1 VALUE2}` either with or without the hack; that's simply how sets have always added their details. You have access to this string in `Formatter` and can do what you want with it. (`option->get_type_name()`) You'll still have to parse the string, though, if you want to change it, but that should be straightforward. The hack doesn't change that, AFAIK. Could you elaborate?

(I'm open to new ideas, too; just remember that from all of CLI11, there is only one Option class)

**Comment by kouchy** [comment]
Ok I understand, it is more clear for me now. No I can't elaborate, it was a misunderstanding: I'm a beginner :-).

Thanks for your time, really.

**Comment by henryiii** [comment]
@kouchy, let me know if you get a chance to try out the Formatting features before 1.6 is released and it's easier to modify if anything is needed or missing.

**Comment by kouchy** [comment]
Ok, I'm not sure if I will try this soon, but if I am I will tell you.

**Comment by henryiii** [comment]
Okay, thanks. If you haven't noticed, the last PR fixed the need for the cludge mentioned above; `add_set` can now schedule a live read of its contents for `get_type_name`.

**Comment by kouchy** [comment]
Yes I saw, I will try this this morning :-). Thank you @henryiii !

**Comment by kouchy** [comment]
Tested! It works like a charm.

**Comment by henryiii** [comment]
@kouchy , due to this behavior tripping up new users with an easy segfault, I'm looking at making it optional in 1.7 by renaming the mutable version to:

```cpp
add_mutable_set(...)
```

(Otherwise the same for now). Would moving to that work for your use case? I'm hoping to work on a redesign of sets for 1.8.
