### ISSUE TITLE
Hybrid flag/option

### ISSUE THREAD

**Issue by sasq64** [CLIUtils/CLI11#124]
I would like to have support for options that can act as flags if no argument is given.
These options would require the forms `-Xsomething` or `--longer=something` when used as options.

```c++
opts.add_hybrid_option("--sign", stringValue, "Sign archive with specified key or default if none given", "defaultKey");

if(stringValue != "") {
  // Perfom signing
}
```
Should print help text such as;
` --sign[=TEXT]`

**Comment by henryiii** [comment]
Just thinking:

This is almost possible currently if you set the min/max allowed options to 0/1, respectively. The requirement of the special forms could be added as an "allowed forms" type option, with flags. Something like: `->allowed_short_form(CLI::NoSpace)->allowed_long_form(CLI::Equals)`.

**Comment by henryiii** [comment]
This is now possible!
