### ISSUE TITLE
optional support (and boost configuration) issue

### ISSUE THREAD

**Issue by jessey-git** [CLIUtils/CLI11#133]
This issue has 2 parts:
- It appears as though the single-file, combined, CLI11.hpp file is built by first assembling the CLI/Optional.hpp file above the CLI/Version.hpp file.  This has the side effect that some defines like CLI11_CPP17 won't be set yet when Optional.hpp starts looking over them.

- There's no way to disable boost support.  The library goes out of its way to detect boost but in my case I kind of don't want it to do that :)  How do I ensure CLI11 doesn't drag in boost headers when I don't want it to?  Maybe use an ALLOW_BOOST define that the user can set before including CLI11.hpp so the lib knows not to check at all.

**Comment by henryiii** [comment]
Fixed ~~in master, and~~ v1.5 branch (I consider this important enough to release a patch release). Please test!

I've fixed the include order issue - it was broken by adding the verbatim sections; the best fix was to put the Version and Macros code in verbatim sections too.

You can now define `CLI11_BOOST_OPTIONAL` to 0 to avoid the search. 1 forces the inclusion, and undefined will do the search.

Note: one side effect: you have to do
```cpp
#define CLI11_BOOST_OPTIONAL 1
```
to force this in user code; before you could forget the 1.

**Comment by jessey-git** [comment]
Both issues seem fixed for me. Thanks!

However, I've now noticed a third issue for MSVC. The usage of "defined(__cpp_lib_optional)" for the
CLI11_STD_OPTIONAL path will cause that to fail.  It's not blocking for me, but for other MSVC users it probably would be.

**Comment by henryiii** [comment]
What is the problem (I'm not as familiar with MSVC as I used to be)? Could you suggest a fix?

**Comment by jessey-git** [comment]
At first glance it could probably be removed entirely from the #if conditional check as it's sufficiently protected otherwise... I think.

Switching my project to /std:c++14 mode will properly skip past, while /std:c++17 and /std:c++latest will properly include <optional> (assuming the __cpp_lib_optional check is removed).  I'm using MSVC 15.7 here but it should be good downwards to 15.3 I would think.

In any case, I don't believe "__cpp_lib_optional" is defined for any compiler?  The closest I could find is "__cpp_lib_experimental_optional" per: http://en.cppreference.com/w/cpp/experimental/lib_extensions

**Comment by henryiii** [comment]
It's listed here: https://en.cppreference.com/w/cpp/experimental/feature_test

I know that __cpp_lib_experimental_optional is not always defined like it should be. Sometimes these headers are present but empty or partial. It might be okay to remove it, but not sure.

**Comment by jessey-git** [comment]
Weird, cppreference's own search pulls up nothing for it :) 

If it is part of the feature test stuff, it will only be available for 15.8 due in a few months I guess: https://twitter.com/StephanTLavavej/status/996830461031677952 

Well, as it stands, there is a workaround after your recent changes -- the MSVC user can explicitly ```#define  CLI11_STD_OPTIONAL 1``` if it's misdetected.

**Comment by henryiii** [comment]
It looks like feature tests are a bit more experimental than I thought. I'll have to revisit those tests (feel free to suggest or make a PR, otherwise it will likely be a week or so).

**Comment by jessey-git** [comment]
The new version seems to work fine in my project after your recent changes - thank you!  You can close as necessary.
