### ISSUE TITLE
Vector options conflict with positional arguments when there is no space.

### ISSUE THREAD

**Issue by ghost** [CLIUtils/CLI11#139]
If you have `-a` as a vector option, and `b` as a positional argument, there will be a conflict when there is no space after the vector option.

```
Usage: ./out [OPTIONS] [b]
```

The following will work fine:
```bash
./out -a 5 positional_value
```
`-a` is parsed as `["5"]` and `b` is parsed as `"positional_value"`.

However, if you do the exact same thing without a space:
```bash
./a out -a5 positional_value
```
`-a` is parsed as `["5", "positional_value"]`, and `b` is not parsed at all.

**Comment by ghost** [comment]
It appears this has been fixed in a more recent release, all that was needed was an update!

**Comment by henryiii** [comment]
I remember that bug. Thanks for checking!
