### ISSUE TITLE
documentation says validator should return void, compiler says validator should return string

### ISSUE THREAD

**Issue by divinity76** [CLIUtils/CLI11#143]
the documentation at https://cliutils.github.io/CLI11/group__validator__group.html says

`These are simple void(std::string&) validators that are useful`

but when i actually give CLI::check() a void(std::string&) , the compiler complains and tells me: 

`candidate: CLI::Option* CLI::Option::check(std::function<std::__cxx11::basic_string<char>(const std::__cxx11::basic_string<char>&)>)`

**Comment by henryiii** [comment]
The problem here is the documentation is not updating; it was changed in 1.6 (maybe even 1.5?) The string is non-empty if the validation fails (and contains the error message to display).

**Comment by divinity76** [comment]
ok, so the string is either empty, or the error message, got it, thanks.

**Comment by henryiii** [comment]
Fixed the issue with the documentation. It's now being deployed again automatically by Travis. (Was missing a path).
