### ISSUE TITLE
what is a validator's returned string supposed to contain? 

### ISSUE THREAD

**Issue by divinity76** [CLIUtils/CLI11#144]
the documentation at https://cliutils.github.io/CLI11/class_c_l_i_1_1_option.html#ab7efde87e06843425c957e706223c5d5 says check() validators are supposed to return a string, but what is this string supposed to contain? 

and as reported in #143 , on some pages the documentation say validators are supposed to return void.

**Comment by henryiii** [comment]
The documentation was changed, but it's not being pushed from Travis for some reason. They contain the error message if validation fails (or empty string for a success).

**Comment by divinity76** [comment]
oh, i see. what is the difference between throwing a CLI::ValidationError and returning an error string?

**Comment by henryiii** [comment]
Returning a string is forward compatible if we ever get an exception-free mode for CLI11. Other than that, they are the same.

**Comment by divinity76** [comment]
gotcha, thanks.
