### ISSUE TITLE
It is unclear how to pass certain arguments via ini file

### ISSUE THREAD

**Issue by Kimundi** [CLIUtils/CLI11#147]
Just from the example given in the README, it is not clear how the syntax works for certain kinds of arguments if passed via a INI config file:

- Positional arguments.
- Subcommands without arguments.
- Options with multiple parameters. (Through trail and error I discovered that its `opt = "foo" "bar" "baz"`

**Comment by henryiii** [comment]
Positional-only arguments, short arguments, and subcommands cannot be passed via an INI file. You can only set the "default" if you will via an INI file - you can set multiple subommand's options, for example; a user may activate one or more of them, or not. If you intend for an option to be available to an INI file, it needs to be given a long optional name. I might add a similar comment, and of course the mention of multiple arguments. Thanks!

**Comment by henryiii** [comment]
Edited, is that better?

**Comment by Kimundi** [comment]
Yeah, the new README is more clear now thanks. :)

I'm wondering why these limitations exists though - I had assumed that a feature for loading commandline arguments from a file would be able to handle all kinds of arguments the library supports.

**Comment by henryiii** [comment]
The idea is to basically "set defaults" on optional arguments, not control the whole app. Forcing a subcommand would be quite odd from a user's perspective. If you really want to customize the command line completely:

`myopts.txt`
```
myposarg mysubcommand --my-flag
```

Then run:
```bash
cat myopts.txt | xargs ./myapp 
```

**Comment by Kimundi** [comment]
Hm, okay, so its basically not intended to work that way per design. I can live with that, did just expect otherwise. :smile: 

Thanks for the feedback (and for reminding me about `xargs`)!
