### ISSUE TITLE
CLI11 shouldn't reset CMAKE_MODULE_PATH

### ISSUE THREAD

**Issue by jdumas** [CLIUtils/CLI11#153]
Hi,

When using this library via `add_subdirectory()` in CMake, I've noticed that it [resets](https://github.com/CLIUtils/CLI11/blob/92b8f6e3bfba72b19bb92b3daad4d0c6ff66fb8e/CMakeLists.txt#L18) the CMake module path:

```cmake
set(CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/cmake" ${CMAKE_MODULE_PATH})
```

I believe it would be preferable to append instead of overriding:

```cmake
list(APPEND CMAKE_MODULE_PATH ${CMAKE_CURRENT_SOURCE_DIR}/cmake)
```

EDIT: Sorry false alarm, was reading this wrong.

**Comment by henryiii** [comment]
Three more points I’ve noticed looking at this: this doesn’t need to append to the path unless coverage is being requested, the CMake minimum version can be adjusted, ~~and the google test cmake file may no longer be used and can be deleted.~~

**Comment by henryiii** [comment]
By the way, FYI, even if the CMAKE_MODULE_PATH was overridden, that's a local set statement - it only affects the current folder and below not the ones above. It would need `CACHE` or `INTERNAL` to do that.

**Comment by jdumas** [comment]
Yes I realized that while debugging another issue in my own project (was just a bit too quick to open this ticket lol). Glad I could help indirectly though =)
