### ISSUE TITLE
Can't make nested subcommands work

### ISSUE THREAD

**Issue by ralbertazzi** [CLIUtils/CLI11#161]
I'm trying to use nested commands, where the "first layer" subcommand has no flag/options but is just a bridge for its subcommands:

```cpp
CLI::App app("Vision Application");
app.set_help_all_flag("--help-all", "Expand all help");
app.add_flag("--version", "Get version");

CLI::App *cameraApp = app.add_subcommand("camera", "Configure the app camera");
cameraApp->require_subcommand(0, 1);   // 0 (default) or 1 camera

std::string mvcamera_config_file = "mvcamera_config.json";
CLI::App *mvcameraApp = cameraApp->add_subcommand("mvcamera", "MatrixVision Camera Configuration");
mvcameraApp->add_option("-c,--config", mvcamera_config_file, "Config filename", true)->check(CLI::ExistingFile);

std::string mock_camera_path;
CLI::App *mockcameraApp = cameraApp->add_subcommand("mock", "Mock Camera Configuration");
mockcameraApp->add_option("-p,--path", mock_camera_path, "Path")->required()->check(CLI::ExistingPath);

CLI11_PARSE(app, argc, argv);
```

This is what I get when running the executable without arguments

```
terminate called after throwing an instance of 'CLI::OptionNotFound'
  what():  mock not found
Aborted (core dumped)
```

This is what I get when running the executable with the option `--help-all`

```
Vision Application
Usage: ./build/nv [OPTIONS] [SUBCOMMAND]

Options:
  -h,--help                   Print this help message and exit
  --help-all                  Expand all help
  --version                   Get version

Subcommands:
camera -> Configure the app camerauser@ubuntu//rest-of-cwd-on-same-line
```

However, if I keep only one layer of subcommands everything works fine:

```cpp
CLI::App app("Vision Application");
app.set_help_all_flag("--help-all", "Expand all help");
app.add_flag("--version", "Get version");

app.require_subcommand(0, 1); // 0 (default) or 1 camera

std::string mvcamera_config_file = "mvcamera_config.json";
CLI::App *mvcameraApp = app.add_subcommand("mvcamera", "MatrixVision Camera Configuration");
mvcameraApp->add_option("-c,--config", mvcamera_config_file, "Config filename", true)->check(CLI::ExistingFile);

std::string mock_camera_path;
CLI::App *mockcameraApp = app.add_subcommand("mock", "Mock Camera Configuration");
mockcameraApp->add_option("-p,--path", mock_camera_path, "Path")->required()->check(CLI::ExistingPath);

CLI11_PARSE(app, argc, argv);
```

Am I missing something about how nested subcommands work? Should I see all my subcommands tree when using the `--help-all` option?

CLI11 Version: 1.6.1   Ubuntu 16.04

**Comment by henryiii** [comment]
`--help-all` expands the options for the subcommands, currently not the inner subcommands, though it might make sense to do that (and forgetting a new line at the end is a mistake! Thanks).

The code you have works for me - I think you are trying to access the subcommand later by asking for an option named `mock` (there isn't one - subcommands and options are separate). If you did throw an OptionNotFound error in the parsing (which you can't), it would be caught by the `CLI11_PARSE` macro and would exit gracefully.

PS: Found some issues in formatting with `--help-all`, it doesn't expand options when it's nested, will prepare a patch. I think I can add the subcommand expansion too.

**Comment by ralbertazzi** [comment]
Well, I found that I didn't change the line AFTER the code that I sent you, which is causing the exception:
```if (app.got_subcommand(mockcameraApp))```

`app` should have been renamed to `cameraApp`

Anyway, yes it would be nice to make --help-all print all the subcommand tree! Thanks!
