### ISSUE TITLE
using CLI11 in a MPI environment

### ISSUE THREAD

**Issue by python152** [CLIUtils/CLI11#162]
hi - 

I have a question of using CLI11 properly in MPI environment (where multiple processes run multiple nodes). The issue with this use case is, I can't just call `CLI11_PARSE()` when error happens, since all MPI processes need a chance to call `MPI_Finalize()` to gracefully exit. 

If a single process just exit without letting others know, you will see bunch of message with segfault, which is not proper for a command line misinput. 
```
[pico:39751] *** Process received signal ***
[pico:39751] Signal: Segmentation fault: 11 (11)
[pico:39751] Signal code: Address not mapped (1)
[pico:39751] Failing at address: 0x0
[pico:39751] [ 0] 0   libsystem_platform.dylib            0x00007fff5d6d1f5a _sigtramp + 26
[pico:39751] [ 1] 0   ???                                 0x0000000000000002 0x0 + 2
[pico:39751] [ 2] 0   pop                                 0x000000010b1d8735 _ZNSt3__111char_traitsIcE6lengthEPKc + 21
[pico:39751] [ 3] 0   pop                                 0x000000010b1c1c9b main + 267
[pico:39751] [ 4] 0   libdyld.dylib                       0x00007fff5d3c3015 start + 1
[pico:39751] *** End of error message ***
Segmentation fault: 11
```

However, if I do the following, it will mess up the "-h" message.

```
       try {
            app.parse(argc, argv);
        } catch (const CLI::ParseError &e) {
        
```    
Any suggestions? thanks

**Comment by henryiii** [comment]
I assume you could do exactly what `CLI11_PARSE` does, but with one line added:

```cpp
try { 
    app.parse(argc, argv);
} catch(const CLI::ParseError &e) {
    int retval = app.exit(e);
    MPI_Finalize();
    return retval;
}
```

Instead of that, I handle MPI in GooFit by putting it into the destructor of a CLI::App subclass. See  

https://github.com/GooFit/GooFit/blob/master/include/goofit/Application.h

and

https://github.com/GooFit/GooFit/blob/33c89d9c72332a613878da77fa7737dec07936a6/src/goofit/Application.cpp#L251-L256

**Comment by python152** [comment]
I suppose the second solution could work.
but the first one is most ideal for me, but there seems to be a problem. I think what is needed:

- put out help or parse error message
- set or return error flags
- let application decide how to exit

`try {} catch {}` method force every process invoke `app.exit(e)` at the end, which in my test still generate segfaults.

**Comment by python152** [comment]
Adding to that, in the case of `app.parse()` generates message along the way, we don't really want every process run it. In other applications, I usually let rank 0 do the parsing, and `MPI_Bcast()` the true/false flag to the rest so they can collectively take actions.

**Comment by python152** [comment]
I think I finally have it work the way I wanted (maybe a bit convoluted), just to close the loop. here it is:

```cpp
bool flag = true
if (rank == 0) {
    // do parsing only by rank 0
    try {
       app.parse(argc,argv);
    } catch (const CLI::ParserError &e) {
       flag = false; // this is the flag indicate parsing error, sent to all other processes
       MPI_Cast(&flag, 1, MPI_CXX_BOOL, 0, MPI_COMM_WORLD);
       app.exit(e); // make sure we unwind the stack
}
/// must call to make collective work
MPI_Bcast(&flag, 1, MPI_CXX_BOOL, 0, MPI_COMM_WORLD); 

/// now all processes know the flag, and they can exit
if (flag) {
      /// parsing is good, proceed to work
}
MPI_Finalize();
```

**Comment by henryiii** [comment]
`app.exit` does not exit - it just returns a exit value and prints the help message (it is not printed from parse). The "return" is what does the exit. So do this:

```cpp
int retval = -1;
try { 
    app.parse(argc, argv);
} catch(const CLI::ParseError &e) {
    if (rank == 0) {
        retval = app.exit(e);
    } else
        // You could broadcast retval, or just:
        retval = 1;
}

if(retval > -1) {
    // cleanup
    MPI_Finalize();
    return retval;
}
```

This way, you still have the values in all the workers from the rest of the parsing (just in case it matters).

**Comment by henryiii** [comment]
PS: I expect the segfault is from `app.exit` printing out text after the finalize. Try my edited first comment, that might be the simplest way to go! If that does work, I could add a note about it somewhere in the docs.

**Comment by python152** [comment]
Yes, I can confirm above flow works, each process will execute `app.parse()`, but only rank 0 will do `app.exit(e)` when error occurs. and `retval` will be the flag to indicate if an error happens and it is available to all processes. There is no need for broadcast. Code is cleaner I think. Thanks for your clarification and help.
