### ISSUE TITLE
add_set()

### ISSUE THREAD

**Issue by python152** [CLIUtils/CLI11#165]
I have an option that is to take a char, similar to gnu find -type f, to search for file.

so:
```
    char type;
    app.add_set("--type", type, {'c', 'f', 'd'}, "by type");
```

and in command line, I tried:

    --type f 
    --type 'f'

None of which works?

**Comment by henryiii** [comment]
I would make it a std::string. A char is actually an 8 bit number in C and C++ (try sending it to cout). You can always get the char out of the string. The length will be okay because of the set you select from.

**Comment by henryiii** [comment]
And always use double quotes, especially for the name of the option!

This is valid code:

```c
int x = 'x';
```

Edit: you fixed the name, much better.

**Comment by python152** [comment]
One issue with std::string is, it requires to use double quote, therefore a '-type f' 
must be typed as 

    --type "f"

which is not natural to some users.

I also tried:

```
    app.add_flag_function("--type", [&](const char c) {
        switch (c)
        {
        case 'd':
            type = c;
            break;
        case 'f':
            type = c;
            break;
        case 'l':
            type = c;
            break;
        default:
            break;
        }
    }, "by type");
```

**Comment by henryiii** [comment]
No, single and double quotes on the command line are not even passed on to programs - single quotes means your shell is not allowed to make substitutions. So "$HOME" is different from '$HOME'. The program (any program) does not even get the outside quotes.

The problem with char is not the check against it, but rather the parse: you are asking for an 8 bit integer. If you did `--type 100` You would get a 'd' , I believe.

**Comment by henryiii** [comment]
That is, "f", 'f', and f are all identical on the command line. They can not be distinguished by any program. (At least in all the shells I am familiar with)

**Comment by henryiii** [comment]
And, you you asked it to take a char, and the user passed `df`, what would happen? How about a single character that was not 8 bits? Logically, you need the string for the initial parse to handle those situations even if require a single char later or from a set.

**Comment by python152** [comment]
I see, string type makes sense to me now.
btw - if I want to do my own validation in lambda function such as `app.add_flag_function()`, what is the proper way to report error message back?

**Comment by henryiii** [comment]
`add_flag_function` is a flag; it does not take arguments (options take arguments). For an option, you return a string message (failure indicated by the string not being empty). However, if you did want a flag to fail, you could throw a `CLI::ValidationError("Message")`.

**Comment by python152** [comment]
got it. thx for the clarification. you have been a great help!
