### ISSUE TITLE
"--help <subcommand>" runs subcommand

### ISSUE THREAD

**Issue by bassjoe** [CLIUtils/CLI11#168]
Would be better if either subcommand's help or a usage error is shown.

**Comment by henryiii** [comment]
This would be a bug. What gets run? The callback, or does it not exit the main function?

**Comment by bassjoe** [comment]
```
#include <iostream>
#include <CLI11.hpp>

int main(int argc, char* argv[]) {
    CLI::App cli_global {"Demo app"};
    auto& cli_sub = *cli_global.add_subcommand("sub", "Some subcommand");
    std::string sub_arg;
    cli_sub.add_option("sub_arg", sub_arg, "Argument for subcommand")->required();
    CLI11_PARSE(cli_global, argc, argv);
    if (cli_sub) {
        std::cout << sub_arg << std::endl;
    }
    return 0;
}
```

I just noticed that without sub_arg it shows the subcommand's help. What I'm trying to achieve is that the sub_arg is required IF the subcommand is called. Maybe I'm doing this wrong.

**Comment by henryiii** [comment]
I believe this is a regression. I think when the short-circuiting behavior was refactored this probably happened.

To be clear, this correctly prints help:
```
$ ./examples/subcom_help sub --help
  Some subcommand
  Usage: ...
```

And this doesn't (and should):

```
$ ./examples/subcom_help --help sub
  sub_arg is required
  Run with --help for more information.
```
