### ISSUE TITLE
Require both options or neither

### ISSUE THREAD

**Issue by devhandle** [CLIUtils/CLI11#175]
**QUESTION**

Hi,

Is it possible to have two options which are dependent on each other being present? I'm using '_needs_' but I'm not able to reference _option_two_ because it hasn't been added yet. I'm see the error _"Option --option_two is not defined"_. 

Thanks.

```cpp
CLI::App app{"TEST"};
app.add_option("-o,--option_one", optOne, "optionOne")->needs("--option_two");
app.add_option("-t,--option_two", optTwo, "optionTwo")->needs("--option_one");
CLI11_PARSE(app, argc, argv);
```

**Comment by henryiii** [comment]
This should work:

```cpp
auto optionOne = app.add_option("-o,--option_one", optOne, "optionOne");
auto optionTwo = app.add_option("-t,--option_two", optTwo, "optionTwo");

optionOne->needs(optionTwo);
optionTwo->needs(optionOne);
```

**Comment by devhandle** [comment]
Yes that works great. Thank you for the quick response.
