### ISSUE TITLE
Required + config files

### ISSUE THREAD

**Issue by henryiii** [CLIUtils/CLI11#176]
Look into required options being provided in config files. Should probably be a "configured" flag on options. Edit: Actually a deeper issue. The parsing sequence needs to be broken up.

**Comment by longhaiqwe** [comment]
Hi, henry. Are you working on this problem? For now I avoid the problem by setting the option not required, but I think it's not the perfect way. Thanks

**Comment by henryiii** [comment]
Since it's a largish issue (requires some restructure of the parse function), I'll be working on it in 1.7, and I don't have time to work on that yet; probably ~1 month if I had to guess.

By the way, this only comes up on subcommands. In the same command you can set required and use a config file to fill it.

**Comment by longhaiqwe** [comment]
Got it!  Waiting for 1.7 ^_^
