### ISSUE TITLE
Calling CLI11_PARSE from outside the main() function.

### ISSUE THREAD

**Issue by devhandle** [CLIUtils/CLI11#180]
Can I call `CLI11_PARSE(app, argc, argv);` from outside the main() function? 

I've written a class and would like to call it from one of it's member function but I'm seeing the exception message _"This should be caught in your main function, see examples"_ instead of the correct parse exception message.

Surely it's possible to call the macro from outside of main()?

**Comment by henryiii** [comment]
Sorry I missed this. I'm sure I wrote at least half a response at one point.

The macro is very simple, and simply expands out to a try catch statement, and a return. The return is why you need to use the macro inside a main function (or some function that's okay returning an error code if the parse fails!). I would simply call `app.parse()` directly, and catch the error yourself.

It's rather hidden in the readme, but this is all the PARSE macro expands to:

```cpp
try {
    app.parse(argc, argv);
} catch (const CLI::ParseError &e) {
    return app.exit(e);
}
```

That's it. `app.exit` is responsible for formatting and printing the error message and gives a return code back.
