### ISSUE TITLE
Callback methods with differing signatures

### ISSUE THREAD

**Issue by helmesjo** [CLIUtils/CLI11#181]
I suppose this is what's already mentioned in the readme:

> In C++14, you could have a set of callback methods with differing signatures (tested in a branch). Not deemed worth having a C++14 variation on API and removed.

Which would be:
```
app.add_option("--run", [&](bool doRun){
    handle_run(doRun);
}, "Set to 1 or 0");
```

IMO this would be very powerful, and avoids a lot of boilerplate code. Currently we can kinda do above, but will have to do the conversion in each callback:
```
app.add_option("--run", [&](std::vector<std::string> results){
    bool doRun;
    if (detail::lexical_cast(results[0], doRun))
        handle_run(doRun);
    return true;
}, "Set to 1 or 0");
```

The latter adds _a lot_ of repetition with just two or three options and is very error prone.

Thoughts? It really shouldn't be too much hassle getting this in, spontaneously thinking, but adds great value.

**Comment by henryiii** [comment]
Quick thoughts:

1. That's not what was mentioned on the Readme - that's actually about a different style of adding options that was in version 0.1. I should remove this or make it clearer.
2. What you are asking is quite a bit simpler to add.
3. It would require a C++14 compatible compiler (though technically wouldn't require C++14 mode, though, as most compilers consider this a bugfix and include it in C++11 mode too). Probably should be restricted to C++14 mode just in case.
4. Unless it's a pull request, I'm not likely to have time to add it until I work on the type system a bit (not soon).

**Comment by henryiii** [comment]
What are the signature(s) that you would like to have?

**Comment by helmesjo** [comment]
> What are the signature(s) that you would like to have?

Basically all that are supported using `add_option` (bool, int, float, std::string etc.).

What I have done in my wrapper allows the following:
```
app.add_option<bool>("--run", [&](bool doRun){
    // ...
}, "Set to 1 or 0");
```
_The type can unfortunately not be deduced from a lambda argument like above unless explicitly instantiated as an std::function object (from what I know), so `<bool>` is required._

**Comment by phlptp** [comment]
In some of my early initial explorations with using CLI  having something like add_option("....",CustomType &T, std::function<CustomType(std::string &arg)>  func)  might be useful, particularly in cases where I have a bunch of arguments to convert from strings.    I suspect this can be done with the existing interfaces but requires the resulting location be specified in the lambda.  Splitting it out would allow custom types behave like double or bool or string.    Just a thought

**Comment by phlptp** [comment]
@helmesjo Do you think what was added in #205 meets what you wanted as far this issue?

**Comment by helmesjo** [comment]
Looks very nice! The ability to have vector of underlying type is a nice touch:
```
app.add_option_function<std::vector<double>>("--val", [&](const auto& vals) {
    // ...
    return true;
});
```

I've been using my CLI11 wrapper with callback-functionality and IMO this is the default way you want to handle options/commands, especially if you have continuous polling of std::cin. Takes very little effort to have a program fully controllable (runtime) using terminal only.

**Comment by phlptp** [comment]
I hadn't really thought about using it like that but you are right it would make creating a terminal program (or command scripting from file) pretty easy to set up.    just read a line and run it through the parser
