### ISSUE TITLE
Validators documentation incorrect

### ISSUE THREAD

**Issue by amerry** [CLIUtils/CLI11#182]
The [validators documentation](https://cliutils.gitlab.io/CLI11Tutorial/chapters/validators.html) does not seem to be valid for the latest release. In particular, the documentation suggests that transformers are set with `->check(func)`, where `func` is `std::string(std::string&)`. However, there is no `check` overload taking this signature.

There is, however, a `->transform(func)` call. That expects a callable with the signature `std::string(std::string)`, taking the original and returning the transformed version, and - unlike `check` callbacks - wants errors to be reported as exceptions (which is fine, but a bit annoying that it's different from `check`).

**Comment by henryiii** [comment]
The correct signature is `std::string(const std::string&)`. It cannot transform it (that's reserved for transform, as you've noted). This was from an older version that did not have the distinction.

If you really want the check to transform, you can do that, but it has to be done with a custom Validator struct. (Edit: I'll fix the documentation soon, before the 1.7 release).

**Comment by henryiii** [comment]
The documentation was technically correct, but confusingly worded. Hopefully it is better now, reopen if there's still a problem! Thanks!

**Comment by amerry** [comment]
It still looks wrong to me.

The [documentation](https://cliutils.gitlab.io/CLI11Tutorial/chapters/validators.html) says:

> A transform validator comes in one form, a function with the signature std::string(std::string &). 

However, the [signature of `transform`](https://github.com/CLIUtils/CLI11/blob/master/include/CLI/Option.hpp#L315) is:

    Option *transform(std::function<std::string(std::string)> func)

meaning the transform validator takes the string argument by value, rather than by reference.

Similarly, the [documentation](https://cliutils.gitlab.io/CLI11Tutorial/chapters/validators.html) says:

> The function will take a string; can optionally transform it, and then returns an empty string if the validation/transformation was successful, or a string with the reason it was not valid.

but the [code](https://github.com/CLIUtils/CLI11/blob/master/include/CLI/Option.hpp#L317) does

    try {
        inout = func(inout);
    } catch(const ValidationError &e) {
        return std::string(e.what());
    }

which means the transform validator should be returning the transformed value, and throwing on validation failure.

**Comment by henryiii** [comment]
I've modified it again. Please open a PR if you can word things better than I can! :)

(Note, it takes a minute for the CI to build the output)

**Comment by amerry** [comment]
Looks good now, thanks! One of the reasons I didn't make a PR in the first place was that I can't figure out where that documentation is generated from.

**Comment by henryiii** [comment]
That's a second issue, I should provide a link in the docs for contributions. :) https://gitlab.com/CLIUtils/CLI11Tutorial

I use GitLab for websites most of the time, because the CI is really easy to setup. (It's now better on Travis than before for GitHub, but I would still have to set up an api key for GitHub and I don't for GitLab).
