### ISSUE TITLE
--help to print default value

### ISSUE THREAD

**Issue by mprat** [CLIUtils/CLI11#188]
I can't seem to find in the documentation anywhere: how do I make running `--help` print the default value for each argument, if the options / flags are optional?

**Comment by henryiii** [comment]
Any option that captures the default value (using `.add_option(..., true)`) will print out the default. If you don't add the `true`, it won't capture the default value, since a type that cannot be converted to a string or an uninitialized value should not be read automatically.

**Comment by mprat** [comment]
Thank you! Works great.

**Comment by deepaktalwardt** [comment]
For anyone who stumbles upon this in the future - this solution doesn't seem to work anymore and causes compilation error. Instead, to display defaults use this `add_option(...)->capture_default_str()`.

**Comment by daiybh** [comment]
Can we have a  a api for  APP, set capture_default_str(true),  
Then we  don't need  call  capture_default_str()  for each option?

**Comment by daiybh** [comment]
Sorry , I found  
`app.option_defaults()->always_capture_default();`

but it don't exist in the book.
