### ISSUE TITLE
Make option description editable (add setter)

### ISSUE THREAD

**Issue by helmesjo** [CLIUtils/CLI11#193]
_(This might apply to program/subcommands as well)_

Glancing over the code, it appears that description is only ever used when parsing arguments (and printing `--help`). I've written a wrapper to CLI11 (custom tailored some stuff for my needs), and being able to set the description after adding an option would be very helpful (and if it doesn't harm...).

Could this be considered?

**Comment by henryiii** [comment]
Sure, it's a simple oversight. Would you like to try a PR adding that? I can, but it might take a while before I can do it.

What things are in your wrapper? Anything interesting? And did you make it as a subclass or did you do something else?

**Comment by henryiii** [comment]
And I know doing `opt->description("...")` was planned at some point, but must have been missed.

**Comment by helmesjo** [comment]
> Sure, it's a simple oversight. Would you like to try a PR adding that? I can, but it might take a while before I can do it.

I'll try to get some time for it! Would you prefer deprecating `get_description()` and add two new:
`std::string description() const`
`void description(const std::string&)`
Or should I simply just add `void set_description(const std::string&);`?

> What things are in your wrapper? Anything interesting? And did you make it as a subclass or did you do something else?

Currently it's pretty much just the functionality mentioned in issue #181. 
Yeah, I opted for hiding the dependency on CLI11, so it's a wrapper (not inheritance, everything touching CLI11 is in the cpp). This means that I've had to explicitly instantiate each option type I want to support (which I considered ok since it's a rather limited set).

**Comment by henryiii** [comment]
CLI11 uses `get_X` to get the value of X, and just `X` to set the value of X. So just add `->description(const std::string&)`, probably to apps and options. And a test or two.

And, on inheritance,
Feel free to look at how GooFit implements CLI11. It's designed to provide a ROOT like interface, but still is powered by CLI11. See [inc][] and [src][].

I think there was nothing against 181, it just wasn't the functionality that was mentioned in the notes.

[inc]: https://github.com/GooFit/GooFit/blob/master/include/goofit/Application.h
[src]: https://github.com/GooFit/GooFit/blob/master/src/goofit/Application.cpp

**Comment by henryiii** [comment]
PS: CLI11 leaves off the "set" because it does not read well with CLI11's chained form. But getters still have `get_` in the name.

**Comment by helmesjo** [comment]
> CLI11 uses `get_X` to get the value of X, and just `X` to set the value of X. So just add `->description(const std::string&)`, probably to apps and options. And a test or two.

Ah, ok!

> And, on inheritance,
> Feel free to look at how GooFit implements CLI11. It's designed to provide a ROOT like interface, but still is powered by CLI11. See [inc](https://github.com/GooFit/GooFit/blob/master/include/goofit/Application.h) and [src](https://github.com/GooFit/GooFit/blob/master/src/goofit/Application.cpp).

Alright, thanks!

> I think there was nothing against 181, it just wasn't the functionality that was mentioned in the notes.

No, not at all. I just had to leave room for customizability on my end anyways, that is why I opted to wrap it (I tend to always wrap dependencies, actually). :)

**Comment by henryiii** [comment]
How's this going? It's a simple enough addition that I'd be okay adding it to 1.7 (in beta phase).

**Comment by helmesjo** [comment]
I'll look into it asap (hopefully today). I'm a little unclear where the "set description after adding option and verify"-test should go... Where would you prefer it?
