### ISSUE TITLE
Quoted arguments with spaces are split up

### ISSUE THREAD

**Issue by Overv** [CLIUtils/CLI11#218]
Given the following program:

```c++
#include <CLI/CLI.hpp>

int main(int argc, char** argv) {
    CLI::App app("foo");

    std::vector<std::string> bar;
    app.add_option("bar", bar, "bar")->required();

    CLI11_PARSE(app, argc, argv);

    for (const auto& entry : bar) {
        std::cout << entry << std::endl;
    }

    return 0;
}
```

I would expect the output to be like this:

```
$ ./program this is a test
this
is
a
test
$ ./program "this is a" test
this is a
test
```

However, the second command instead prints the words separately just like the first command. This seems like a bug caused by #209.

**Comment by henryiii** [comment]
Should be an easy fix. The default should not be `' '`, and instead should be "empty" or null, and then ignored if so.

**Comment by henryiii** [comment]
@rafiw, do you think you could change the default char `'\0'`, then skip the loop breaking up the string if that's the case? Otherwise I can do it in a couple of days. PS: I recommend using a branch rather than master of your fork if you make a PR. It gives me an odd feeling force-pushing to a master, even if it is a fork.

**Comment by rafiw** [comment]
@henryiii yes master was me been lazy editing the file from the github site.
i will push a PR soon

**Comment by henryiii** [comment]
@rafiw Thanks!

**Comment by rafiw** [comment]
i changed a bit the code now i get the following when using ',' as a delimiter

```
./a.out "this is" a,test "3 3" 4,4,4,4
this is
a
test
3 3
4
4
4
4
./a.out "this is" a,test 3 3 4,4,4,4
this is
a
test
3
3
4
4
4
4
./a.out "this is a,test 3 3 4,4,4,4"
this is a
test 3 3 4
4
4
4
// when specifying no delimiter
./a.out "this is" a,test "3 3" 4,4,4,4
this is
a,test
3 3
4,4,4,4
./a.out this is a test
this
is
a
test
./a.out "this is a" test
this is a
test
```
@henryiii ok?

**Comment by Overv** [comment]
@rafiw Thanks for the quick followup, that looks good to me at least :+1:

**Comment by henryiii** [comment]
@rafiw I like it! Feel free to add that little prog as an example, those can get tested too.
