### ISSUE TITLE
add_option with bool?

### ISSUE THREAD

**Issue by abrownsword** [CLIUtils/CLI11#224]
I have a use case for being able to use this syntax:    —option=true

Synonyms like yes/no or on/off would be nice.  I have a hacked solution using a callback_t but I don’t see why bool isn’t a first class citizen?

**Comment by henryiii** [comment]
I believe this was added in #219 (will be in 1.8). It would be a flag.

**Comment by henryiii** [comment]
The only difference is that you can't force a value. `--option=true` and `--option` would be equivalent.

**Comment by phlptp** [comment]
I believe after #219 having `bool` value in add_option supports `--option=true`, `--option disable` and a number of other synonyms of true and false.  

The difference between the `add_option(XXX, bool)` and `add_flag(XXX, bool)` is that in the option version an argument is required,  in the flag version only the `--option=<XX>` syntax is supported but it has a default value so `--option`  with no arguments uses a default value (usually true) 

Adding a few more tests with `add_option(XXX,bool,...` would probably be good just to make sure

**Comment by abrownsword** [comment]
I didn't see mention of this particular syntax in #219, but then again I'm on the last release, not on HEAD.  I'll give it a go when the next release is posted.

**Comment by phlptp** [comment]
I don't think there was a syntax change as far as the options go, just internally it handles bool's in options consistently between flags, options and ini files, where there was some discrepancies before, at least that was the idea.

**Comment by henryiii** [comment]
Added some tests in my Sets PR, it does look like this syntax now works. :)

**Comment by henryiii** [comment]
Tests are now part of master, and it's mentioned in the README and CHANGELOG, so I think it's okay to close this.
