### ISSUE TITLE
changing add_option_function

### ISSUE THREAD

**Issue by phlptp** [CLIUtils/CLI11#252]
@henryiii 
In integrating CLI11 into our application I had several cases to use add_option_function.  However in none of those cases would the function naturally return a bool, so they all had to wrapped in lambda which just returned true at the end.    I think it would be more convenient if the the functions had a void return type. Which now as I look at the documentation is what the README actually says, so that needs to be fixed either in the code or in the README.  

I thought of a couple different options.  
1. just changing the return type to void and making a note in the docs about throwing an error if it fails.  
2. Adding a add_option_callback method that actually takes a void return type function
3.  Templating the function on the Callable and some template trickery to dealing with bool/void return types.  

Option 1 is by far the simplest,  I don't know that I like 2. and 3 is more work but would be the most flexible, though would come at a compile time cost.

**Comment by henryiii** [comment]
I think option 1 is okay, since the readme says that already. I went with bool because I was trying to someday allow compiling CLI11 with exceptions turned off, but I don't know if that will ever happen.
