### ISSUE TITLE
Different subcommands cannot require a positional argument with the same name

### ISSUE THREAD

**Issue by Overv** [CLIUtils/CLI11#256]
When multiple subcommands require a positional argument with the same name, it seems that the requirement is never met:

```c++
#include <CLI/CLI.hpp>

int main(int argc, char** argv) {
    CLI::App app("A simple app");
    app.set_help_all_flag("--help-all", "Expand all help");
    app.require_subcommand();

    std::string bar;

    CLI::App* fooApp = app.add_subcommand("foo", "Foo a bar");
    fooApp->add_option("bar", bar, "A bar to foo")->required();
    
    CLI::App* bazApp = app.add_subcommand("baz", "Baz a bar");
    bazApp->add_option("bar", bar, "A bar a baz")->required();
    
    CLI11_PARSE(app, argc, argv);
}
```

```
$ ./app foo abc
bar is required
Run with --help or --help-all for more information.
$ ./app baz abc
bar is required
Run with --help or --help-all for more information.
```

Seems that this started happening after #227.

**Comment by phlptp** [comment]
I will add a test in #251 that checks to make sure that can work.  I know some other related issues were resolved in that PR but I don't know that particular situation was checked.

**Comment by phlptp** [comment]
I added a test and it passes in #251 So I think when that gets merged this issue should be resolved.

**Comment by Overv** [comment]
Cool, thanks for the quick response.

**Comment by phlptp** [comment]
@Overv  have you been able to verify this works for you in the latest master?

**Comment by Overv** [comment]
@phlptp Yeah, this is definitely fixed.
