### ISSUE TITLE
How to create CLI11.hpp from latest master

### ISSUE THREAD

**Issue by pramodk** [CLIUtils/CLI11#258]
Hello,

Thanks for nice CLI utility! I am currently using CLI11 as git submodule but it's bit inconvenient because of it's own git submodule size : 

```
$ du -h -d 2 .
448K	./include/CLI
448K	./include
448K	./tests
192K	./docs
0	./.github
32K	./cmake
32K	./.ci
32K	./extern/sanitizers
9.3M	./extern/googletest
243M	./extern/json
253M	./extern
0	./test_package
0	./examples/subcom_in_files
32K	./examples
32K	./scripts
254M
```
Using latest release is not an option because I would like to use some of the recent feature/fixes. 

Instead of adding multiple header files, I would like to have single CLI11.hpp as provided with release. Could you please provide instructions to build one from the master?

**Comment by henryiii** [comment]
I probably should make proper instructions somewhere; there'a nice little branding feature in the generation script that lets users customize the namespace and macro prefix.

Anyway, here are initial instructions:

From the CLI11 directory, run:

```bash
./scripts/MakeSingleHeader.py CLI11.hpp
```

Python3 is recommended, though it works with Python 2.6+. Run with `-h` for help.

By the way, the submodules are only used for testing and examples, so if you can avoid them being recursively checked out, it will still work fine.

**Comment by pramodk** [comment]
thank you @henryiii !
