### ISSUE TITLE
Enum example not working

### ISSUE THREAD

**Issue by infinity0n3** [CLIUtils/CLI11#263]
Version: 1.7.1 CLI11.hpp 

The `examples/enum.cpp` example cannot be compiled as CLI::CheckedTransformer cannot be found anymore.

Has this functionality been removed?

**Comment by phlptp** [comment]
The [CheckedTransformer](https://github.com/CLIUtils/CLI11/pull/239) is something that is only available in the master branch I don't think it was available when 1.7.1 was released.    The enum example was also updated at that time.

**Comment by henryiii** [comment]
The examples are all built and tested in CI as well, so you probably are using CLI11 1.7.1 and the master branch for the example, if I had to guess.

**Comment by infinity0n3** [comment]
You are completely right. 1.7.1 does not support it yet.
Thanks for the quick answer.
