### ISSUE TITLE
Standardizing the license

### ISSUE THREAD

**Issue by ghost** [CLIUtils/CLI11#267]
The license reads like a 3-clause BSD...can we standardize it?

**Comment by henryiii** [comment]
It was written by a University of Cincinnati lawyer. Don’t think it can change.

**Comment by dtarakanov1** [comment]
BTW, why didn't your lawyer use something better as a template, e.g. MIT or BSD-2-Clause license?

Using a BSD-3-Clause-like license just prevent wider use of your library.
E.g. we're developing a product which is going to be open sourced under the MIT license later, so we'll just have to find some other library with a compatible license or write our own.
I believe this is not how open source is expected to work.

BTW, MIT is also a university so obviously there should no be any issues.
