### ISSUE TITLE
name validation on subcommands

### ISSUE THREAD

**Issue by phlptp** [CLIUtils/CLI11#272]
As we were integrating CLI11 into our applications, there was one location where we were using add_subcommand and had transposed the name and the description.  Everything ran normally until we go to a some tests where the subcommand would be called and nothing happened.  Due to the nature of the code it took a while to find the issue.    

What I am wondering about is whether add_subcommand should have a check on the name.  For example a simple check on whether the name contained any spaces would immediately distinguish it from most descriptions and catch that error pretty quickly.  

I suppose in theory you could have a subcommand name with spaces  and use quotes on the command line to trigger it, but I don't imagine that is a common case, and if a name restriction is in add_subcommand there is a workaround even for that situation.  Subcommands with a '-' or '--' in front could be problematic as well.    

So I am wondering if there should be a check in add_subcommand on the name and what the nature of that check should be,  a runtime check and throw,  an assert, or something else?

**Comment by henryiii** [comment]
Just curious, would `app.add_subcommand("name")->description("This is a discription");` be better for avoiding mistakes?

**Comment by phlptp** [comment]
definitely, but that would require deprecating the two string version to be effective.
