### ISSUE TITLE
App does not exit when --help

### ISSUE THREAD

**Issue by sy6sy2** [CLIUtils/CLI11#276]
Hi,

If the user does `./foo --help` then the help message is printed but the application does not exit (the code after `CLI11_PARSE(app, argc, argv);` is executed).

How to catch the `--help` flag, or better, directly quit the app when the user use `--help`?

Thank you.

**Comment by henryiii** [comment]
`CLI11_PARSE` has a `return 0` in it, so it does exit if it's in `main`. If it's not in main, I would write the contents of `CLI11_PARSE` out explicitly, then do whatever you expect when the exit exception is thrown.

**Comment by henryiii** [comment]
This is all `CLI11_PARSE(app, argc, argv)` expands to:

```cpp
try {
    app.parse(argc, argv);
} catch (const CLI::ParseError &e) {
    return app.exit(e);
}
```

This catches `CallForHelp`.

**Comment by sy6sy2** [comment]
Oh ok I understand now! Thank you very munch!
