### ISSUE TITLE
Feature Request: ->needs() but for a specific Option value

### ISSUE THREAD

**Issue by alterscape** [CLIUtils/CLI11#282]
I need to specify a mode option, like `--mode ["foo", "bar", "baz"] (default is "foo")`. Depending on whether foo, baz, or bar is selected, different options are required and/or allowed.  This seems a lot like subcommands, but specified as an option, rather than a one of several flags. Is there a way to do this?  `->needs()` is almost what I want, but it only checks that an option is specified, not what it is set to.

**Comment by phlptp** [comment]
This is one of the use cases for option_groups.  There are a couple different ways of setting this up.  

Each option set related to one of the modes can be set up in a different option_group.   with the "foo" group being `enabled_by_default` and the others `disabled_by_default` 

Then place the mode option in another mode group.  add an `IsMember` or `CheckedTransformer` validator to make sure it is a valid Value and add a `preparse_callback` to the mode group that enables or disables the appropriate option groups.    Inside the preparse callback lambda you can query the value of mode   `app["--mode"]->as<std::string>()` to get the current value.

**Comment by phlptp** [comment]
The other way I have done something similar is to just have the --mode option in the main app.  Then in the callback for the main App, have a few other Apps that can be selected from and do the processing. 

Just have to make sure the app. has `enable_extras()` enabled and use `subApp.parse(app.remaining_for_passthrough())`

**Comment by alterscape** [comment]
Thank you! I ended up solving my problem with your second solution, which nicely compartmentalizes options. The one special case it doesn't happen is when `foo` and `bar` both take option `baz`, but `narf` doesn't.  In that case I need to add `baz` to both the `foo` and `bar` apps, but that's not the worst thing and maybe reflects a bigger structural change that's required in my code-base. Thank you!

**Comment by phlptp** [comment]
With one option it probably simpler to add it twice, but if there were a group of options that needed to be included in multiple apps, it is possible to place those options in a group and with the shared_ptr or nameless app add them to both sub applications.

**Comment by phlptp** [comment]
One disadvantage of the second option is the "help" doesn't display correctly on its own, so it would need to be setup manually.  

Glad you were able to get something working!
