### ISSUE TITLE
Plans for 1.9

### ISSUE THREAD

**Issue by henryiii** [CLIUtils/CLI11#283]
There are other additions for 1.9, most likely, but this is what I'd like to go in:

- [x] Remove deprecated parts that have warnings
    - adding warnings to remaining deprecated parts not easy since they are templated functions.
- [x] I'm also highly considering dropping support for GCC 4.7 in 1.9 or the next version; please speak up if you need it!
- [x] Move the tutorial to this repository

For 1.9.1 or 2.0:

- Update the tutorial for 1.8+ (keeping it in sync eventually?!)

**Comment by phlptp** [comment]
In the near term some things I am planning to work on or have somewhat ready to go

- [x] Support for tuples in the add_option
- [x] a footer callback
- [x] rework the app callbacks to add a dedicated third callback to simplify callback timing
- [x] add a needs function for option_groups for options issue #291 
- [x] support vector of pair, tuple
- [x] #362   config file refactor
- [x] address #371 
- [] do some work on the book related to option groups (for 2.0)

**Comment by phlptp** [comment]
I am starting to look at the ini file processing.  There are a few open issues regarding the files that might be able to be dealt with reasonably.

**Comment by phlptp** [comment]
I am not going to get to anything related to the book in the next week, so feel free to make a release @henryiii to 1.9 if you think appropriate.  Getting the book up to date for a future 2.0 release would probably be important though.

**Comment by henryiii** [comment]
Okay, I'll probably make the release in the next couple of days.

**Comment by alkino** [comment]
Should be close
