### ISSUE TITLE
Exclude to exclude positional

### ISSUE THREAD

**Issue by SuperWig** [CLIUtils/CLI11#287]
Would it be possible to have `excludes` to exclude that option in positionals?

e.g I have
```
app [input] [output]
```
And have an option for using an example input. So if that's supplied would want
```
app --example [output]
```

**Comment by phlptp** [comment]
There are a couple ways of doing this.  If `--example`, [input], and [output] are placed in separate option_groups.  Then you can use the 
`void TriggerOff(App *trigger_app, App *app_to_enable)`    with the option_groups to set the `--example` group to turn of the input group.

One other possibility is having an option_group with just the '--example'  but in a pre parse callback for that group load something into the input option `inputOpt->add_result(example_file_name)`  then CLI11 will think it is filled out already and skip it.  (I haven't tried this but I think it should work that way).

**Comment by SuperWig** [comment]
That works, thanks :)
