### ISSUE TITLE
Add needs(option_or_subcommand) option for subcommand

### ISSUE THREAD

**Issue by Bouska** [CLIUtils/CLI11#291]
Currently .excludes() exists for options, options groups and subcommands, but .needs() only exists for option.

In my case, some of my subcommands require a printer and therefore the parameters for that printer. I have a option group at the top app that are used for this, but I can't currently enforce they are present when I use the printer related subcommands. Is there a workaround the lack of .needs() or could it be implemented in the next releases?

**Comment by phlptp** [comment]
I thought about this earlier, but there are a few corner-cases that were not obvious how to deal with and it wasn't required for the work we were doing at the time, so it never got implemented.   

If I understand what you want is a `.needs(...)` method  on an option_group/subcommand that requires another option_group/subcommand to be used as well?  

As far as what to do at present you could use the TriggerOn(printer_app,   vector of apps_requiring_printer) function to only enable those apps requiring a printer after the printer was specified.    

Or in the callbacks of the different apps do a check if the count_all() in the printer group>0  and throw a `RequiresError` if it doesn't.

**Comment by Bouska** [comment]
In my case, I would have used `.needs(...)` method with a list of options pointers (or names) because I'm still figuring out how to use option groups without messing the help output, but the idea is the same.

I'm going to try both of your ideas to see if that works for me.

**Comment by phlptp** [comment]
a needs function has been added for apps and subcommands with support for options and other subcommands.
