### ISSUE TITLE
seg-fault when clearing config file option

### ISSUE THREAD

**Issue by projekcja** [CLIUtils/CLI11#298]
In the docs:

> Option * | set_config (std::string option_name="", std::string default_filename="", std::string help_message="Read an ini file", bool config_required=false)
> -- | --
>   | Set a configuration ini file option, or clear it if no name passed.
> 

Seems like calling set_config(); with no name doesn't stop the app from trying to read a configuration file.

My code that causes seg-fault:

```
#include "CLI/CLI.hpp"

#include <stdio.h>
#include <stdlib.h>
#include <string>

int main(int argc, char **argv) {
    
	CLI::App app("my app");

	int volume= 0;
	app.add_option("--volume", volume, "volume1");
	
	app.set_config("--config", "cfg.ini", "Read an ini file", false);
	app.set_config(); //  clears config option if no name is passed. 
	
	int is_interactive_mode = 0;
	app.add_flag("-i,--interactive", is_interactive_mode, "Interactive mode");
	
	app.parse(argc, argv);
	std::cout<<"Volume: "<<volume<<std::endl;

	return 0;	
}

```

**Comment by henryiii** [comment]
Thanks for catching that!
