### ISSUE TITLE
User defined config file

### ISSUE THREAD

**Issue by infinity0n3** [CLIUtils/CLI11#30]
When using `add_config` option and passing a custom filename for the config file it is not loaded.
`app.add_config("-c,--config", "config.ini", "Read config from an ini file", false);`
`>> app --config custom_config.ini`

Ini parsing code in App.hpp should be something like this to make it work.

```cpp
        // Process an INI file
        if(config_ptr_ != nullptr && config_name_ != "") {
            auto user_config = config_ptr_->results();
            
            // take user passed filename into account
            if( config_ptr_->count() ) {
                config_name_ = config_ptr_->results()[0];
            }
            
            try {
                std::vector<detail::ini_ret_t> values = detail::parse_ini(config_name_);
                while(!values.empty()) {
                    if(!_parse_ini(values)) {
                        throw ExtrasINIError(values.back().fullname);
                    }
                }
            } catch(const FileError &) {
                if(config_required_)
                    throw;
            }
        }

```

**Comment by henryiii** [comment]
I implemented a similar fix, I just used the existing callback infrastructure (`config_ptr_->run_callback()`), and I also added a requirement that user-supplied names must be found. Also added the missing tests.

**Comment by henryiii** [comment]
It would be great if you could verify this fix works in your case, too!

**Comment by infinity0n3** [comment]
Fix works great!
