### ISSUE TITLE
Set flag to false

### ISSUE THREAD

**Issue by jbriales** [CLIUtils/CLI11#303]
Is there any way to override a passed flag to false?
I.e. say I call `foo --gui` where `--gui` is a bool flag. Is there anyway I can make that flag false with a subsequent option and using `take_last()`. Something like `foo --gui --gui=false` or `foo --gui --no-gui`?

NOTE: The reason for overriding is cases where we don't have direct access to the base command.

**Comment by phlptp** [comment]
as long as you are using a recent release `--gui=false` or `--gui=0` should work.

you an also add a flag like
```
app.add_flag("--gui,--no-gui{false}",gui_flag,"add a gui");
```

then `--no-gui` would be a false flag,  and with a bool variable  I believe take_last should be the default.

**Comment by jbriales** [comment]
Awesome! Thanks so much! I didn't find all this info in the documentation. I'll give it a try asap :)

**Comment by henryiii** [comment]
What do you mean by the documentation? The README, the gitbook, etc?

**Comment by jbriales** [comment]
Yes, I didn't find anything in a first quick screening.
Now searching again for `{false}` I realized this info is in https://github.com/CLIUtils/CLI11#option-types
It's not however in https://cliutils.gitlab.io/CLI11Tutorial/chapters/flags.html
As a friendly comment, I often find searching for details in https://github.com/CLIUtils/CLI11 daunting as the sections are a little bit large and not so fine-grained. And I'm also confused about which info/level of detail there is in https://github.com/CLIUtils/CLI11 vs https://cliutils.gitlab.io/CLI11Tutorial/
