### ISSUE TITLE
ExistingFileValidator fail for file > 2GB on Windows

### ISSUE THREAD

**Issue by zyzheng** [CLIUtils/CLI11#312]
When using with a video file that is larger than 2GB, `ExistingFileValidator` always fails even if the file actually exists.

From the [code](https://github.com/CLIUtils/CLI11/blob/06ab2d0fbde14e093da65fa292e60d7d988d3c26/include/CLI/Validators.hpp#L224), it's using `stat` to check file stats. According to [Microsoft document](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/stat-functions?view=vs-2019#time-type-and-file-length-type-variations-of-_stat), it seems that function only support up to 32bit file length, which I assume is the cause for this problem.

I think using `_stat64` on Windows should fix it, but not sure about other operating system.

**Comment by henryiii** [comment]
I believe other platforms return 64-bits from stat. Probably needs a check for windows + 64 bit...

**Comment by steffenb7333** [comment]
Since it is a CMAKE-define (CLI11_CXX_STD) would it not be an option to use std::filesystem::* if CLI11 is/was compiled using c++17 and/or a Feature Testing Macro indicates it is available?
