### ISSUE TITLE
Non-single-header linking error

### ISSUE THREAD

**Issue by andreca** [CLIUtils/CLI11#316]
`include/CLI/ConfigFwd.hpp:95: error: undefined reference to `vtable for CLI::ConfigINI'`

The linker reports the above error when the first member function `std::string to_config(...)` of `CLI::ConfigINI` is declared, but not defined.

I'm using gcc 7.4.0

**Comment by henryiii** [comment]
The "Fwd" indicates that it does not include the definitions, just the declarations. At some point you have to include `"include/CLI/Config.hpp"`.

**Comment by andreca** [comment]
I'm currently including :
* `App.hpp`
* `Formatter.hpp`
* `Validators.hpp`

in different files. I guess its `App.hpp` thats pulling in `ConfigFwd.hpp` so either I have to explicitly include `Config.hpp` or just stick with `CLI.hpp`?

**Comment by henryiii** [comment]
Include `Config.hpp` for now, and 2.0 should fix this properly. CLI11 was originally designed to be used with `CLI.hpp`, but 2.0 will properly support this sort of thing.
