### ISSUE TITLE
CI failures

### ISSUE THREAD

**Issue by phlptp** [CLIUtils/CLI11#324]
There appear to be some issues with the CI test for clang 3.4 and gcc 4.8 on travis and azure,
the badge for Azure is showing up as a failure and doesn't direct anywhere.  

As a note travis is slowly shifting all projects to travisci.com so I would expect this to occur at some point, which will require fixing the links in some of the badges.

**Comment by henryiii** [comment]
I’m visiting family this week in CA, will try to work on this at done point. I would like to move to Travisci.com, but they didn’t have a tool to do so yet last I checked.

**Comment by henryiii** [comment]
I'll debug this soon. I've added CLIUtils to the Travis Migration Beta waitlist.
