### ISSUE TITLE
non-const App::get_options

### ISSUE THREAD

**Issue by jbriales** [CLIUtils/CLI11#326]
I was looking for how to iterate over all options (concretely, inside a option group), to set certain parameter of the option.
I found `get_options` but this is const-only.
Would it be possible to add a non-const version of `get_options` for an App?
I.e. just
`std::vector<Option *> get_options() { return options_; }`

**Comment by phlptp** [comment]
My guess is this is another case of no one needing it so it was never added.  One other possibility would seem to match your use case would be an `apply` method that applies an operation to each contained option.
