### ISSUE TITLE
CLI::PositiveNumber not working with float types

### ISSUE THREAD

**Issue by steffenb7333** [CLIUtils/CLI11#328]
CLI::PositiveNumber calls detail::lexical_cast which in turn uses std::stoull and so any float type produces an error.

**Comment by phlptp** [comment]
looking at this a little closer, the positiveNumber validator should probably be split into two validators.  A NonNegative validator which simply checks that there isn't a '-' as the first character. and a PositiveNumber template which also checks for a specific type with an actual positive number but the conversion check is with multiple types.
