### ISSUE TITLE
clang format version differences

### ISSUE THREAD

**Issue by phlptp** [CLIUtils/CLI11#331]
It looks like there are a few differences in the versions of clang-format that impact the code formatting and therefore the CI test concerning such.  

see [build](https://dev.azure.com/CLIUtils/CLI11/_build/results?buildId=337)

I did verify that the older and newer clang-format produce different results.  So either the check needs to be updated to a newer version or we need to specify an exact version of clang-format to use.

**Comment by henryiii** [comment]
I also probably need to disable color output because Azure doesn't seem to handle it like it used to.

**Comment by phlptp** [comment]
This appears to be resolved
