### ISSUE TITLE
Hidden option is displayed with (no|incorrect) args

### ISSUE THREAD

**Issue by skannan89** [CLIUtils/CLI11#332]
Love your library! I noticed a small issue. I added three flags and made one of them hidden. 

Code Snippet:
```
app.add_flag("--flagA", "flag A");
app.add_flag("--flagB", "flag B");
app.add_flag("--flagC", "flag C")->group("");
app.require_option(1, 1); // Require exactly one flag
```

The hidden flag is not displayed in help message. When I specify no or incorrect arguments, it prints the hidden flag. 

```
# myutil
Exactly 1 option from [--flagA,--flagB,--flagC] is required
Run with --help for more information.

# myutil --fla
Exactly 1 option from [--flagA,--flagB,--flagC] is required
Run with --help for more information.

# myutil --help

[Exactly 1 of the following options is required]
Usage: myutil [OPTIONS]

Options:
  -h,--help            Print this help message and exit
  --flagA              flag A
  --flagB              flag B
```

Please let me know if I am using the library wrong. Thanks for your help.

**Comment by skannan89** [comment]
Found the [bug](https://github.com/CLIUtils/CLI11/blob/master/include/CLI/Option.hpp#L627) in `Option::get_name()`. Adding this line ~inside each for loop~ in the function fixes the bug:

```
if(detail::to_lower(get_group()).empty()) {                                                                                                                                                                                                            
   return {}; // Hidden
}
```

I can get a PR ready early next week.

**Comment by henryiii** [comment]
I'll be working on the CI next week (currently failing), then will be merging and reviewing PRs. Thanks for the catch!
