### ISSUE TITLE
Subcommand should void required arguments not part of the subcommand

### ISSUE THREAD

**Issue by robiwano** [CLIUtils/CLI11#347]
If I have an application which, without the subcommand, requires an argument, when using the subcommand, that argument is still required.

**Comment by robiwano** [comment]
I.e.
`app.add_option("--option", option, "Required option")->required();`
and
```
auto sub = app.add_subcommand("test", "Testing");
sub->add_option("--test-option", test_option, "Test option");
```
Running my app with `app test --test-option "my option"` results in:
`--option is required`

**Comment by phlptp** [comment]
I would argue this behavior is expected and desired.  I know I have used that before for required options with subcommands.

to get the above desired behavior it would be possible to put the required option in an option group
```cpp
auto req_group=app.add_option_group("required");
req_group.add_option("--option", option, "Required option")->required();

auto sub = app.add_subcommand("test", "Testing");
sub->add_option("--test-option", test_option, "Test option");

sub->excludes(req_group);
```

If this doesn't work that would likely be considered a bug, while I would consider the above behavior the desired results.

**Comment by robiwano** [comment]
Indeed, thank you. I knew there had to be a way.
