### ISSUE TITLE
Set default option values from parent App

### ISSUE THREAD

**Issue by jbriales** [CLIUtils/CLI11#352]
I'm wondering if it would be possible to have a behavior as follows for passing options:
Consider we have a `cmd` with subcommands `foo` and `bar`. Both `foo` and `bar` may take some option `--sth`, i.e. `cmd foo --sth 10 ... bar --sth 10`.
Is there any existing feature by which I could have `cmd --sth 10 foo ... bar ...` set `--sth 10` for both `foo` and `bar` subcommands, i.e. inherit the default value from a homonymous parent option?

I'm working with some nested subcommands for a complex CLI app and this feature would come in handy :)

**Comment by phlptp** [comment]
subcommands can allow fallthrough,  which means options in the parent app(or an option group of the parent) can be used as part of the subcommand.  

not sure if that is what you are looking for or not.    I wasn't sure if you wanted distinct options that just inherited or a single option that can be used like it was in the subcommand.

**Comment by henryiii** [comment]
Reopen if there's something to be done here. I think fallthrough covers some cases and when it doesn't, you could have a custom callback.
