### ISSUE TITLE
nvcc warnings

### ISSUE THREAD

**Issue by ferdymercury** [CLIUtils/CLI11#359]
when using nvcc as compiler, I get some warnings:

/CLI/TypeTools.hpp(143): warning: invalid narrowing conversion from...

I guess there are some guards there for GCC, but could be expanded for NVCC compiler.

**Comment by phlptp** [comment]
I have never used NVCC,  If there is a way to do something similar for NVCC  to  block the warning could you submit a PR?

**Comment by henryiii** [comment]
I can at least check this; I think we can check the build for warnings in CI with docker (tried earlier, but having some space issues with Docker locally)

**Comment by ferdymercury** [comment]
There are some preprocessor variables defined that might do the job like:
```
__CUDA_ARCH__
__CUDACC__
```

See https://stackoverflow.com/questions/8796369/cuda-and-nvcc-using-the-preprocessor-to-choose-between-float-or-double
https://devtalk.nvidia.com/default/topic/368814/cuda-programming-and-performance/defines-automatically-defined-by-nvcc-/

**Comment by henryiii** [comment]
This should be tested now in CI and fixed!
