### ISSUE TITLE
Question: Accept value beginnig with `-`

### ISSUE THREAD

**Issue by mody** [CLIUtils/CLI11#361]
Hi!

I have this option:
```
std::vector<std::string> ranges;
app->add_option("-r,--by-record-num", ranges, "Comma-separated records or record ranges");
```

In older version I was able to parse command like like this:
```
./a.out -r -1 -r 4-
```
In `v.1.8.0` I get 
```
The following argument was not expected: -1
```

I tried to add `->expected(-1)` to the `add_option()` but it still refuses to accept the command line.

How should I parse it?

**Comment by phlptp** [comment]
You might need to use the latest master instead of release 1.8.  I recall a bug about that being fixed not that long ago.  If it still doesn't work in master let us know.

**Comment by mody** [comment]
I can confirm, that it works on `master`.

So I'll wait for the next release. Thanks!
