### ISSUE TITLE
geninfo exclusion markers are not terminated (properly)

### ISSUE THREAD

**Issue by cmoore3** [CLIUtils/CLI11#375]
When collecting code coverage using [lcov](http://ltp.sourceforge.net/coverage/lcov.php), the capture step emits a warning about its exclusion markers not being terminated:
```
geninfo: WARNING: unterminated exclusion section in CLI11/include/CLI/App.hpp
```

According to the [geninfo docs](http://ltp.sourceforge.net/coverage/lcov/geninfo.1.php), the markers are terminated via `LCOV_EXCL_STOP` (not `LCOV_EXCL_END`).

This project contains markers like this:
```
        // LCOV_EXCL_START
        throw(OptionAlreadyAdded("added option matched existing option name"));
        // LCOV_EXCL_END
```
https://github.com/CLIUtils/CLI11/blob/master/include/CLI/App.hpp#L557
https://github.com/CLIUtils/CLI11/blob/master/include/CLI/App.hpp#L2491

**Comment by sergeyklay** [comment]
Oh, I faced with exactly this warning regarding CLI11's App.hpp every day. Finally I just added 2>/dev/null at the end.

**Comment by phlptp** [comment]
I wondered about that and never could figure out exactly why,  there seems to be differing documentation on // LCOV_EXCL_END since I have seen that documented in other places.
