### ISSUE TITLE
Required flags not being informed as such by the help message

### ISSUE THREAD

**Issue by vhborges** [CLIUtils/CLI11#386]
This can be seen on the [subcom_partitioned](https://github.com/CLIUtils/CLI11/blob/master/examples/subcom_partitioned.cpp) example in this repo: when run with _--help_, the _--count_ flag will not be informed as required, despite it being so (not using it produces an error).

Is this an expected behaviour?

**Edit:** changed "--help-all" to "--help"

**Comment by phlptp** [comment]
if --help is used with this example
```
This is a timer: 4.1 us
K3Pi goofit fitter
Usage: C:\Users\phlpt\Documents\CLI11\build\examples\Debug\subcom_partitioned.exe [OPTIONS]

Options:
  -h,--help                   Print this help message and exit
[Option Group: Subcommands]
  Important
  Positionals:
    file TEXT REQUIRED          File name
  Options:
    -f,--file TEXT REQUIRED     File name
    -c,--count REQUIRED         Counter
[Option Group: Subcommands]
  Other
  Options:
    -d,--double FLOAT           Some Value
```

So the REQUIRED shows up

**Comment by phlptp** [comment]
The --help-all option is not enabled for this example
so running with a --help-all option will just show a warning message since the flag is unrecognized

```
This is a timer: 3.9 us
--file is required
Run with --help for more information.
```
if an actual help-all flag is added then 
```
This is a timer: 9.3 us
K3Pi goofit fitter
Usage: C:\Users\phlpt\Documents\CLI11\build\examples\Debug\subcom_partitioned.exe [OPTIONS]

Options:
  -h,--help                   Print this help message and exit
  --help-all
[Option Group: Subcommands]
  Important
  Positionals:
    file TEXT REQUIRED          File name
  Options:
    -f,--file TEXT REQUIRED     File name
    -c,--count REQUIRED         Counter
[Option Group: Subcommands]
  Other
  Options:
    -d,--double FLOAT           Some Value

```

so it shows up correctly.

**Comment by phlptp** [comment]
What seems to be clear though is that more indication of an `ERROR` is needed so it wouldn't be mistaken for a help, and perhaps enabling help-all by default.  
Also would probably benefit from #173

**Comment by vhborges** [comment]
Sorry, I actually meant --help instead of --help-all.

On my computer the REQUIRED is not shown with --help (using gcc/g++ version 9.2.0 and CLI11 version 1.8), look:

![Screenshot_20200101_141629](https://user-images.githubusercontent.com/31579741/71644068-5b386200-2ca1-11ea-859d-4c46bdaa1f73.png)

**Comment by phlptp** [comment]
OK, That is interesting.    Can you check with the latest master just to make sure it wasn't updated recently?

**Comment by vhborges** [comment]
Indeed it appears to be fixed on master. Sorry for not checking it before.

![Screenshot_20200101_143611](https://user-images.githubusercontent.com/31579741/71644253-27ab0700-2ca4-11ea-85e1-c25ea9a92158.png)

**Comment by phlptp** [comment]
Great!  That certainly wasn't an issue we knowingly fixed but I remember some updates around the code that generates the output recently so thought there was a chance it was resolved in master.  

Thanks!

**Comment by henryiii** [comment]
Going to close since this seems to be resolved in the next release without any work, the best kind of issue. ;)
