### ISSUE TITLE
Enable a vector option to consume all arguments following the first string in the vector

### ISSUE THREAD

**Issue by zadjii-msft** [CLIUtils/CLI11#417]
Enable a vector option to consume all arguments following the first string in the vector

In the [Windows Terminal](https://github.com/microsoft/terminal), we're [adding support](https://github.com/microsoft/terminal/pull/4023) for using CLI11 to handle parsing our commandline. We've got a subcommand that lets users specify a commandline to run in a new tab, like the following:

```
wt new-tab cmd.exe /k doTheThing.exe
```

`new-tab` is the subcommand here, and `cmd.exe /k doTheThing.exe` is the commandline the user is trying to run in the new tab. `new-tab` also supports a number of other options, for example, `-d <working directory>` to set the initial directory the tab opens in.

However, we've run into a bit of a problem where the options to a user's commandline might conflict with the options to `new-tab` itself. Consider the following commandline:

```
wt new-tab wsl -d Ubuntu
```

In the above commandline, the user is trying to open a new tab running their Ubuntu distro in WSL with the commandline `wsl -d Ubuntu`. However, by default, this gets treated by CLI11 as:
1. Set the working directory to `Ubuntu` (from `-d Ubuntu`) 
2. Run the commandline `wsl`

We're aware that there's a workaround currently, where users could instead specify `wt new-tab -- wsl -d Ubuntu` to have everything after the `--` treated as the commandline. However, we'd really love to keep the behavior where everything after (and including) `wsl` is all treated as the commandline. 

We've implemented our own workaround at the moment where we manually collect all the arguments after the first commandline string (in this case `wsl`) into the commandline, but it feels especially hacky at the moment.

Is there a way to do this easily with CLI11 currently that I'm missing? If there's not, would it be possible to add support to CLI11 directly to enable such a scenario?

/cc @DHowett-MSFT

**Comment by phlptp** [comment]
If I understand what you are doing correctly, here is what I think would work.  

```cpp
auto ntab=app.add_subcommand("new-tab");
std::string cmd;
ntab->add_option("cmd",cmd);
std::vector<std::string> cmd_args;
ntab->add_option("cmd_args",cmd_args);
ntab->positionals_at_end(true);  
```

what this will do is treat everything after the first positional as more positionals regardless of whether they look like an option or not.   The `positionals_at_end` modifier is what makes this work.  

then you would have to use those two arguments for whatever your subcommand actually does.

**Comment by henryiii** [comment]
This is called a `->prefix_command()`. It can take options, but as soon as something that is not an option is encountered, it collect the rest to send it somewhere else - you access the left over with `->remaining()`. Example:

https://wandbox.org/permlink/zk2z4S5ctlu81h7i

```c++
#include "CLI11.hpp"
#include <iostream>
#include <string>

int main(int argc, char** argv) {
    
    CLI::App app("Windows Terminal");
    
    auto new_tab = app.add_subcommand("new-tab");
    new_tab->prefix_command();
    
    std::string dir;
    new_tab->add_option("-d", dir, "working directory");
    
    CLI11_PARSE(app, argc, argv);
 
    std::cout << "-d: " << dir << "\n";
    for(auto&& item : new_tab->remaining())
        std::cout << item << " ";
    std::cout << std::endl;
    return 0;
}
```

(if you put the `-d` before the `wsl`, it will be read as an option)

**Comment by DHowett-MSFT** [comment]
Thanks for the info here! It looks like `positionals_at_end` is a little closer to what we want, because it supports `--` without breaking the subcommand.

I like the elegance of `prefix_command` and the `remaining()` vector, but here's what I saw:

## `prefix_command`

### `wt.exe new-tab -d test -- wsl -d Alpine`

This is parsed as `new-tab -d test` and then some loose options, `Alpine` `-d` `wsl`. The `--` terminates the subcommand instead of the argument list for the subcommand.

I've also seen instances where remaining contains `--` itself.

## `positionals_at_end`

We have to maintain a string and a vector, but it works as expected with `--` (the arguments all end up in `cmd_args`, but a single `--` ends up in `remaining`... even if `cmd_args` contains another `--` (which is great!)

**Comment by phlptp** [comment]
It shouldn't be necessary to use a '--' with `positionals_at_end` and you could use a single vector if you wanted all positionals in a single vector.  The separation into a string and vector was for illustration purposes.    You may also want to look at `remaining_for_passthrough` which should have a different order for the remaining args meant to passthrough to another app.

**Comment by DHowett-MSFT** [comment]
We ended up with a single vector and `positionals_at_end`. It looks like this feature request can be closed out. Thanks again!
