### ISSUE TITLE
Can I change the value name of an option in the help message?

### ISSUE THREAD

**Issue by unageek** [CLIUtils/CLI11#418]
Do you have something like `value_name` of Boost.Program_options?

**Comment by phlptp** [comment]
I think what you are looking is `type_name`.  That is what controls what gets printed after the option name.  like `TEXT` or `FLOAT`.  This can be specified as a callback function or a string.  

like 
```
"-f,--file TEXT REQUIRED"
"-d,--double FLOAT"
```

**Comment by unageek** [comment]
That's it! Thank you very much!
