### ISSUE TITLE
Question: have an option similar to help in comportment

### ISSUE THREAD

**Issue by alkino** [CLIUtils/CLI11#426]
Hi,

First of all, thanks for your library.

I would like to have a `--version` option which behave like `--help`.
Meaning:
* Don't check for validity of other options (for example required ones).
* Do nothing, leave it right after (but return 0, help return a code != 0).

Is it possible today? I play with `add_flag` with lambdas, `.excludes`, but cannot achieve that.

Regards

**Comment by phlptp** [comment]
We had a similar desire, what we used was 
```cpp
add_flag_callback("--version,-v", []() { throw(CLI::Success{}); });
```

Then [later on in the processing](https://github.com/GMLC-TDC/HELICS/blob/master/src/helics/core/helicsCLI11.hpp#L82) we catch the CLI::Success and print out the version number.    If you had multiple callbacks like that you can check which one was actually called something like 
```cpp
if (!app["--version"]->empty())
```



the code is [here](https://github.com/GMLC-TDC/HELICS/blob/master/src/helics/core/helicsCLI11.hpp) for the full wrapper program 

If you wanted to use the CLI11 macros I believe you can just place the version printing statements in the callback before the throw and I think CLI11 will handle that correctly; CLI::Success has a return code of 0.

**Comment by alkino** [comment]
Nice way to do it. Thanks for the advice.
