### ISSUE TITLE
config file issues

### ISSUE THREAD

**Issue by ncoder-1** [CLIUtils/CLI11#440]
Hi,

First, it looks like there's a documentation issue.  
For `config_to_str`, the main page and the [Config file page](https://cliutils.github.io/CLI11/book/chapters/config.html) states that it has 3 arguments, `(default_also=false, prefix="", write_description=false)` but in reality, the code (at least in release 1.9.0) only has 2 arguments (`default_also` and `write_description`).

Second and the actual issue I'm having is with the following test code:

```cpp
#include <string>
#include <vector>

#include "include/CLI11.hpp"

using std::cout;
using std::string;
using std::vector;

struct SampleStruct {
  int someValue{9000};
};

auto main(int argc, char** argv) -> int {
  vector<string> input_file{};
  string output_file{"test.txt"};
  bool verbose_output{false};
  SampleStruct samplestruct;

  CLI::App app{"testapp"};

  app.allow_extras(true);

  app.add_option("-i", input_file, "input file")->check(CLI::ExistingFile);
  app.add_option("-o", output_file, "output file", true);
  app.add_option("-s", samplestruct.someValue, "some value", true);
  app.add_flag("-v", verbose_output, "verbose output");

  cout << app.config_to_str(true, true) << '\n';  //before

  app.allow_config_extras(false);
  app.set_config("--config", "main.conf", "Read a config file", false);

  cout << app.config_to_str(true, true) << '\n';  //after

  try {
    app.parse(argc, argv);
  } catch (const CLI::ParseError& e) {
    return app.exit(e);
  }
  cout << app.config_to_str(true, true) << '\n';  //after again
}
```

If I have no config files that exist, the output is the following:
```
; testapp

; testapp

; testapp

```
Shouldn't it output a INI file with the option variables and its default values?

If I do have a config file witch contains only `output_file = "another.txt"`, the output is then:
```
; testapp

; testapp

INI was not able to parse output_file
Run with --help for more information.
```

What am I doing wrong here?

Thanks!

**Comment by phlptp** [comment]
I will look into that a little more.  
For debugging purposes what version are you using, and have you tried this with the master branch?

**Comment by ncoder-1** [comment]
I was using release 1.9.0.  I just tried with master and the only difference is TOML output instead of classic INI.

```
# testapp

# testapp

INI was not able to parse output_file
Run with --help for more information.
```

**Comment by phlptp** [comment]
ok, I haven't tried the output side of the config parser too much other than the test cases, but I will get back to you on the issue

**Comment by phlptp** [comment]
It looks like the config generator will only print values for which a long argument name is present.  So in the above case all the arguments only have short names, so they don't get printed in the config.   

 I am not totally sure if that was just an oversight or on purpose.  @henryiii ?    Though it looks like it would also print out incorrectly if there was a value in this case.  Probably should be fixed to allow using a short argument if no long form exists.  

for the ini input file there is no argument named output_file so that input is unrecognized.  and since you have `allow_config_extras(false)`  that generates an error.  It would probably have to be 
`o="another.txt"` for it to register.

**Comment by ncoder-1** [comment]
Thanks for your answer.

For the ini input file, I tried with `o="another.txt"` and not much luck:

```
# testapp

# testapp

INI was not able to parse o
Run with --help for more information.
```

Also note that `--help` doesn't actually work in this case when the config file is not parsed properly.

**Comment by phlptp** [comment]
I am working on a fix,  if you want to take a look at https://github.com/phlptp/CLI11/tree/config_short.  I think that fixes the issue you were having with the config output.

**Comment by ncoder-1** [comment]
I can confirm that it now works with that fix! Thanks!

It might be worth mentioning in the documentation that `config_to_str()` should be used after the `try/catch` block if you want to output the modified config after reading a config file.  Otherwise, only thing left is to remove the `prefix=""` argument from the documentation.

**Comment by phlptp** [comment]
I do need to update docs and books yet and maybe test a few more things before it is ready.  But good to know it works for you.

**Comment by phlptp** [comment]
The docs are updated if you want to have a look @elimpnick

**Comment by ncoder-1** [comment]
Yep that works!  Feel free to close this as solved.  Thanks again!

**Comment by phlptp** [comment]
This issue should get closed when the PR gets merged.
