### ISSUE TITLE
Possibilities to use string with space

### ISSUE THREAD

**Issue by RegisGraptin** [CLIUtils/CLI11#441]
Hello,

I would like to know if it's possible to use as a parameter a string with space.
For example, I would like to have a flag which will have a string as input like "my name".

`my-app --name="my app"`

I don't know if it's already possible and how I to do it, if i need to add a specific option ?

```
 CLI::App app{"My app."};

  std::string name = "default name";
  app.add_option("--name", name, "Name");

  CLI11_PARSE(app, argc, argv);
```

Best regards

**Comment by phlptp** [comment]
Strings with spaces shouldn't be in issue as long as the shell feeds them in as single argument string.  Which typically means they need to be enclosed in quotes in the shell.

**Comment by RegisGraptin** [comment]
Ok, I found what was the problem it was my mistake.
I have an intermediary script for running my program to Docker.
Sorry about that, and thanks for the help.

Best regards
