### ISSUE TITLE
Design-issue regarding the return type of add_flag

### ISSUE THREAD

**Issue by steffenb7333** [CLIUtils/CLI11#444]
This is something I just stumbled upon in my own code and was the cause of a nasty bug which was very hard to find.

Consider the following code:

```
bool test(bool something)
{
  if (something){} // crash
  return something;
}
int main()
{
  CLI::App app{"app"};
  auto something_flag = app.add_flag("--something", "something");
  CLI11_PARSE(app, argc, argv);
  test(something_flag);
}
```

This will always call `test(true)` (and crash), irregardless of the actual command line parameters. The Option* returned by add_flag is implicitly converted to a boolean which is always true.

`test(*something_flag);` does not compile, because CLI::Option cannot be implicitly converted to bool, but must be explicitly converted: `test(static_cast<bool>(something_flag));`

Irregardless of that being a bit unintuitive, the implicit conversion of the Option* to bool may be a serious source of hard to find bugs.

**Comment by phlptp** [comment]
The implicit conversion of a pointer to a bool is pretty well embedded in C/C++ and can't really be changed.   Things like clang-tidy can usually catch them and  recommend some modifications.  But that certainly isn't going to change  in C++.    

Do you think there are some things that could be done in CLI11 that would help in this situations?

**Comment by steffenb7333** [comment]
Do not return a pointer but a value/object instead.

**Comment by henryiii** [comment]
Pointers avoid copies. References were not possible, they are way too easy to accidentally copy. The problem here is you are using auto and it is hiding the return type and causing the easy confusion. You can use `->count() > 0`.

The design here may change slightly for 2.0, though. Will keep this in mind, but it's not very likely to change too much.

**Comment by steffenb7333** [comment]
My counter-point regarding the avoid-a-copy-issue is that parsing command line arguments does not happen in a time-critical code-path 99.9% of the time.
So returning a non-implicit-convertible proxy-object of some kind and maybe improving code-safety by not allowing surprising conversions or similar cases is more beneficial than avoiding an extra copy or two and saving nanoseconds in CPU-time.

Anyway, my solution at the moment to avoid any similar mistakes is to only use the add_flag-overloads which take an extra variable by reference to store the result and I am fine with that as a workaround. So I am also closing the issue because from my point of view there is no immediate need for action.
