### ISSUE TITLE
Undefined reference to std::filesystem::status in C++17

### ISSUE THREAD

**Issue by timothyqiu** [CLIUtils/CLI11#445]
I'm using CLI11 1.9.0 with gcc 8.3.0 on Debian 10, and I tried the single header version, a manual install, and the Conan package.

If the main project is in C++17, then by default, using CLI11 produces an undefined reference error when linking:

```
/usr/bin/ld: CMakeFiles/demo.dir/main.cpp.o: in function `CLI::detail::check_path(char const*)':
main.cpp:(.text._ZN3CLI6detail10check_pathEPKc[_ZN3CLI6detail10check_pathEPKc]+0x38): undefined reference to `std::filesystem::status(std::filesystem::__cxx11::path const&, std::error_code&)'
/usr/bin/ld: CMakeFiles/demo.dir/main.cpp.o: in function `std::filesystem::__cxx11::path::path<char const*, std::filesystem::__cxx11::path>(char const* const&, std::filesystem::__cxx11::path::format)':
main.cpp:(.text._ZNSt10filesystem7__cxx114pathC2IPKcS1_EERKT_NS1_6formatE[_ZNSt10filesystem7__cxx114pathC2IPKcS1_EERKT_NS1_6formatE]+0x64): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

This is because gcc < 9 requires a separate library `libstdc++fs` for `std::filesystem`.

I think this is a CLI11 issue because when using CMake, the target `CLI11::CLI11` is supposed to specify all its required libraries, so a `target_link_libraries(demo PRIVATE CLI11::CLI11)` is enough for the user.

The current workaround is to manually adding the missing libraries or defining `CLI11_HAS_FILESYSTEM=0` to disable the `std::filesystem` approach.

A possible solution is to detect the correct libraries, as discussed [here](https://gitlab.kitware.com/cmake/cmake/issues/17834). For example using something similar to this [FindFilesystem.cmake](https://github.com/vector-of-bool/CMakeCM/blob/master/modules/FindFilesystem.cmake).

**Comment by phlptp** [comment]
Despite some trouble with azure, we are able to replicate the issue so it will be fixed soon.  Thanks for identifying the issue.    See #446
