### ISSUE TITLE
Show alias of subcommands in help

### ISSUE THREAD

**Issue by berhoeckner** [CLIUtils/CLI11#448]
Hi,

is there a way to show aliases of subcommands in the help?

And is it possible to have a seperate description? Or extend the description?

Thanks!

**Comment by phlptp** [comment]
Separate description for each alias, probably not.  showing in the help, that might be doable.

**Comment by phlptp** [comment]
I was tinkering with something to show aliases in the help

would the preference be for something like this 
```
  sub1                         description
     aliases:                   sub_alias1, sub_alias2
```

or 
```
sub1, sub_alias1, sub_alias2 
                                 description                     
```

I am not sure which I prefer

**Comment by berhoeckner** [comment]
both options look fine to me

maybe a slight preference for the second option 
```
sub1, sub_alias1, sub_alias2 
                                 description      
```

or an overly verbose combination:

```
sub1, sub_alias1, sub_alias2 
                                 description    
                                 aliases: sub_alias1, sub_alias2  
```
