### ISSUE TITLE
run callback crashed

### ISSUE THREAD

**Issue by goudan-er** [CLIUtils/CLI11#453]
```cpp
#include <CLI/CLI11.hpp>
#include <iostream>
#include <string>

struct Client {
  std::string ca;
};

class Admin {
 public:
  Admin() : Admin("instance admin") {}
  Admin(const std::string &name) : app_(name) {}
  ~Admin() = default;

  void Init() {
    app_.set_help_all_flag("--help-all", "Expand all help");
    app_.add_option("--ca", ca_file_, "ca file")->required();
    app_.parse_complete_callback([&] {
      std::cout << "parse_complete_callback start" << std::endl;
      client_ = new Client;
      client_->ca = ca_file_;
      std::cout << "parse_complete_callback finish" << std::endl;
    });

    std::string instance_uri;
    app_.add_option("--instance_uri", instance_uri_, "the instance uri")
        ->required();

    RegisterCreateCommand();
  }

  int Run(int argc, char **argv) {
    app_.require_subcommand(1);
    CLI11_PARSE(app_, argc, argv);
    return 0;
  }

 private:
  void RegisterCreateCommand() {
    std::string *instance_name = new std::string;
    CLI::App *create_instance =
        app_.add_subcommand("create_instance", "create a instance");
    create_instance->add_option("--name", *instance_name, "the instance name");
    create_instance->final_callback([this, &instance_name] {
      std::cout << "final_callback start" << std::endl;
      printf("create instance: linstance_name=%s\n", instance_name->c_str());
      printf("instance_uri=%s, ca=%s\n", instance_uri_.c_str(),
             ca_file_.c_str());
      std::cout << "final_callback finish" << std::endl;
    });
  }

  CLI::App app_;
  std::string instance_uri_;
  std::string ca_file_;
  Client *client_;
};

int main(int argc, char **argv) {
  Admin admin{"test admin"};
  admin.Init();
  return admin.Run(argc, argv);
}
```
This is a demo. The line `create_instance->final_callback([this, &instance_name] {...` add a final callback for app. But it will crash due to the `instance_name` memory is corruption. However, If `instance_name` is captured by value, the demo can run correctly. I try to deep into CLI11 and it seems CLI11 will not modify the memory of assign_to_value.

**Comment by phlptp** [comment]
`instance_name` is a local variable in the `RegisterCreateCommand()` stack.  once that function finishes it is destroyed, and the pointer itself no longer exists, and any reference to it is dangling.  The string it points to still exists but if you capture by reference in the lambda it it essentially a reference to a memory location that no longer exists, and if you try to use it is undefined behavior.  You need to capture by value in this case or it is undefined behavior on the pointer location itself, not the allocated memory.

**Comment by goudan-er** [comment]
> `instance_name` is a local variable in the `RegisterCreateCommand()` stack. once that function finishes it is destroyed, and the pointer itself no longer exists, and any reference to it is dangling. The string it points to still exists but if you capture by reference in the lambda it it essentially a reference to a memory location that no longer exists, and if you try to use it is undefined behavior. You need to capture by value in this case or it is undefined behavior on the pointer location itself, not the allocated memory.

thanks...
