### ISSUE TITLE
Problems with MPI on Mac

### ISSUE THREAD

**Issue by pavanakumar** [CLIUtils/CLI11#454]
Hi

I am trying to run CLI11 using MPICH-3.3 on mac (using gcc-8 from homebrew) and facing a peculiar problem. CLI11 does not seem to print the help message on ParseError. It simple aborts.

```
$> g++ simple.cpp
$> ./a.out
--file is required
Run with --help for more information.
```

But the same program compiled using the MPI wrapper

```
$> mpic++ simple.cpp
$> ./a.out
[1]    32360 abort      ./a.out
```

The help message or any of the error messages are not being printed. Any idea why this is happening?

**Comment by phlptp** [comment]
Not really,  MPI programs are always a little tricky to handle the shutdown process.  Depends on when you initialized the MPI stuff.   Are you using CLI_PARSE?

**Comment by pavanakumar** [comment]
No I do not use CLI_PARSE and make my point of failure only on the master rank (0). This is how my overall structure looks like

```c++
int main(int nargs, char *args[]) {
  MPI_Init(&nargs, &args);
  MyApp app(nargs, args);
  MPI_Finalize();
```
The MyApp is defined as follows

```c++
class MyApp : public CLI::App {

    MyApp(int nargs, char *args[])
      : CLI::App{"MyApp : This is MyApp"} {
       int rank;
       MPI_Comm_rank(MPI_COMM_WORLD, &rank);
       this->add_option("--file", m_file, "The input file name")->required();
        try {      
          this->parse(nargs, args);
        }
        catch (const CLI::ParseError &e) {
          if (rank == 0)
            this->exit(e);
        }
  }
};
```

**Comment by phlptp** [comment]
what happens if you run with `--help` in both cases?  I presume the non-mpi version displays help properly, but what does the MPI version do?

**Comment by pavanakumar** [comment]
The non-mpi version gives the correct help message. But the mpi version shows this error output

```
$> mpirun -np 2 ./a.out --help
===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 48468 RUNNING AT 192.168.1.6
=   EXIT CODE: 6
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Abort trap: 6 (signal 6)
This typically refers to a problem with your application.
Please see the FAQ page for debugging suggestions
```

**Comment by phlptp** [comment]
It seems like somehow the exception is leaking out the constructor you have thought I don't really understand what is going on.   Maybe you can try something like 

```cpp
int main(int nargs, char *args[]) {
  MPI_Init(&nargs, &args);
  try {
       MyApp app(nargs, args);
  } catch (...) {
     std::cout<<" unexpected error"<<std::endl;
  }
  MPI_Finalize();
```

and try to debug from there to figure out what is going on.

**Comment by pavanakumar** [comment]
This seems to be a mac specific issue related to MPI as I cannot reproduce this in Linux. So I am closing this thread as this does not seem to be an issue with CLI11. If anyone thinks this is a CLI11 issue please feel free to reopen this thread.
