### ISSUE TITLE
Not compatible with C++20

### ISSUE THREAD

**Issue by F-I-D-O** [CLIUtils/CLI11#458]
In C++20 std::result_of is removed (Used in App.hpp).

**Comment by phlptp** [comment]
what compiler are you using that generates an error?  and what flags?

**Comment by F-I-D-O** [comment]
I use Visual Studio 2019 Preview 5.0. But this should be a general issue of all C++20 ready compilers, as std::result of is removed in C++20 (https://en.cppreference.com/w/cpp/types/result_of)

**Comment by phlptp** [comment]
@F-I-D-O Are you actually getting it to generate an error?  I am not able to get an error on the result_of in any compilers I try.  I know how to fix it, but I was hoping to see a failing test first.

**Comment by F-I-D-O** [comment]
Yes:
`C:\vcpkg\installed\x64-windows\include\CLI/App.hpp(3055): error C2039: 'result_of': is not a member of 'std'`
`C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.26.28801\include\numeric(23): note: see declaration of 'std'`
`C:\vcpkg\installed\x64-windows\include\CLI/App.hpp(3055): error C2653: 'result_of': is not a class or namespace name`
`C:\vcpkg\installed\x64-windows\include\CLI/App.hpp(3055): error C3646: 'type': unknown override specifier`
`C:\vcpkg\installed\x64-windows\include\CLI/App.hpp(3062): error C2039: 'result_of': is not a member of 'std'`
`C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.26.28801\include\numeric(23): note: see declaration of 'std'`
`C:\vcpkg\installed\x64-windows\include\CLI/App.hpp(3062): error C2653: 'result_of': is not a class or namespace name`
`C:\vcpkg\installed\x64-windows\include\CLI/App.hpp(3062): error C3646: 'type': unknown override specifier`

This is a result of compilation of your example code, i.e.:

    int main(int argc, char** argv) {
        CLI::App app{"App description"};

        std::string filename = "default";
        app.add_option("-f,--file", filename, "A help string");

        CLI11_PARSE(app, argc, argv);
        return 0;
    }

**Comment by phlptp** [comment]
@F-I-D-O  would you mind trying the changed code in #459.  Just to make sure?  It is enabled for C++14 and higher, but I want to make sure it resolves the error you are seeing.

**Comment by F-I-D-O** [comment]
I can try it on in a couple of days. Does it mean that I try it with the branch `phlptp:cpp20_test`? Or something more sophisticated :)

**Comment by 0vercl0k** [comment]
fwiw @phlptp your changes in #459 fixed this issue for me on VS2019 latest.

**Comment by henryiii** [comment]
Please reopen if this is not working on master (that's merged now)!
