### ISSUE TITLE
app.parse() bugged in Visual Studio 2019 ?

### ISSUE THREAD

**Issue by Antimoscientifico** [CLIUtils/CLI11#460]
I was studying CLI11 for the first time, but when I tried to compile a couple of examples that contain **app.parse(__argc, __argv);** in VS 2019 the compiler crashes with this error message:

_Microsoft C ++ exception: CLI :: CallForHelp in memory location 0x00000032CCEFEC10._

This only happens when I set the -h argument to the program. **If instead of app.parse(__argc, __argv); I use CLI11_PARSE(app,__argc, __argv);  everything works without problems.**

This is the code I tried to compile:
```
#include <iostream>
#include "CLI11.hpp"

int main() {
	using std::cout;
	using std::endl;
	CLI::App app{ "Flag example program" };

	
	bool flag_bool;
	app.add_flag("--bool,-b", flag_bool, "This is a bool flag");

	int flag_int;
	app.add_flag("-i,--int", flag_int, "This is an int flag");

	CLI::Option* flag_plain = app.add_flag(
		"--plain,-p", "This is a plain flag");
	

	
try {
	//CLI11_PARSE(app,__argc,__argv);
	app.parse(__argc, __argv);
}
catch (const CLI::ParseError& e) {
	std::cout << e.what();
	return app.exit(e);
}
	

	
	cout << "The flags program" << endl;
	if (flag_bool)
		cout << "Bool flag passed" << endl;
	if (flag_int > 0)
		cout << "Flag int: " << flag_int << endl;
	if (*flag_plain)
		cout << "Flag plain: " << flag_plain->count() << endl;
	
return 0;
}
```

**Comment by henryiii** [comment]
I believe you are missing a return?You need to return if an exception was caught.

**Comment by Antimoscientifico** [comment]
> I believe you are missing a return?You need to return if an exception was caught.

Oops, it was my writing mistake. Unfortunately it is not `return 0;` :(

**Comment by henryiii** [comment]
```cpp
return app.exit(e);
```

That computes the return code from the exception.

**Comment by Antimoscientifico** [comment]
> ```c++
> return app.exit(e);
> ```
> 
> That computes the return code from the exception.

Sorry I understood another thing, even trying to add **return app.exit(e);** I get this message:

_`_This should be caught in your main function, see examples_`_

But I think I wrote the try and catch in the main function.


```
try {
	//CLI11_PARSE(app,__argc,__argv);
	app.parse(__argc, __argv);
}
catch (const CLI::ParseError& e) {
	std::cout << e.what();
	return app.exit(e);
}
```

**Comment by henryiii** [comment]
```cpp
try {
	//CLI11_PARSE(app,__argc,__argv);
	app.parse(__argc, __argv);
}
catch (const CLI::ParseError& e) {
	return app.exit(e);
}
```

The `app.exit` function prints for you before returning the error code; `std::cout << e.what();` prints out a warning that `app.exit` will correctly hide.

**Comment by henryiii** [comment]
PS: If you want to implement yourself, `e.get_exit_code()` is the exit code. And here's the code for app.exit: https://github.com/CLIUtils/CLI11/blob/c439562abbd991c78047030223030e9924c374a9/include/CLI/App.hpp#L1331-L1354

**Comment by Antimoscientifico** [comment]
Thanks so much for the info now I understand.
Fortunately, this is not a bug.
