### ISSUE TITLE
Allow sequence of single char options like -vv -vvv

### ISSUE THREAD

**Issue by patlecat** [CLIUtils/CLI11#462]
The lib is behaving weird when I try to define a "-vv", no errors but some parts of my code won't execute anymore.

Request:
It would be really good if I could define a "-v", "-vv" and a "-vvv" to make it easier for the user instead of forcing him to enter the long "--" options.

**Comment by phlptp** [comment]
Are you working on the master branch or v1.9?  The behavior of this may have changed slightly in master.  

In general defining a `-v` is a single character option  calling -vv on the command line would be the same as calling -v -v.    The effect this has depends on the output argument for the flag.  If the argument given was a boolean then the second will have no effect.  If the argument was an integer, then the result will be a count of the number of times the single argument was called.

'-v' would result in 1,
'-vv' would result in 2
'-vvv' would result in 3

**Comment by patlecat** [comment]
Yeah, I'm working with the master. And yes, I'm aware of the count. But i'd prefer to have a proper -vvv option for something like very-very-verbose. So that's not gonna come anytime soon?

**Comment by henryiii** [comment]
You can write:

```cpp
int verbose;
app.add_flag("-v",  verbose);
```

And then, if you pass `-vvv`, after the `CLI11_PARSE` this would set verbose to 3. That's why int is supported here, actually. What other thing would you expect to have happen?

**Comment by patlecat** [comment]
But this also means that if someone enters `myapp.exe -v -g -v -z -v` then the count would also return 3 for "-v" right? But that's a bit ambiguous and less clear than 1 option of "-vvv".

**Comment by phlptp** [comment]
In general I agree with the philosophy of CLI11 that single dash long form options are non-standard and should not in general be allowed.  

If I really wanted single dash long form options.  I would probably do something like this. (written as a test)
```cpp
    bool verbose{false};
    bool veryverbose{false};
    bool veryveryverbose{false};
    app.name("testargs");  // needed to ensure final callback runs(though the conditions for this maybe should be fixed
    app.allow_extras();
    args = {"-v", "-vv", "-vvv"};
    app.final_callback([&]() {
        auto rem = app.remaining();
        for(auto &arg : rem) {
            if(arg == "-v") {
                verbose = true;
            }
            if(arg == "-vv") {
                veryverbose = true;
            }
            if(arg == "-vvv") {
                veryveryverbose = true;
            }
        }
    });
    run();
    EXPECT_EQ(app.remaining().size(), 3U);
    EXPECT_TRUE(verbose);
    EXPECT_TRUE(veryverbose);
    EXPECT_TRUE(veryveryverbose);
```

might be worth investigating help generation for something like this in the future.  But I don't think direct support for single dash long form options should be supported.

**Comment by henryiii** [comment]
Parsing is a bit of a language. A single dash is a contract between you and your user. `-vvv` is expected to be identical to `-v -v -v` as long as `-v` does not take an option; I think if is was not you should indicate this to the user by using `--`, which is exactly what that is supposed to mean. `--v`, `--vv`, and `--vvv` are clearly marked as three distinct options, and a user will not expect `--v --v` to be the same as `--vv`.

As seen above, CLI11 gives you the freedom to do unusual things that confuse users, but it generally does not try to help you.
