### ISSUE TITLE
Is there some missing preparse callback call ?

### ISSUE THREAD

**Issue by dfleury2** [CLIUtils/CLI11#463]
Hi,
here a sample, with a conf file.
```cpp
#define CLI11_HAS_FILESYSTEM 1
#include "CLI11.hpp"

#include <iostream>
#include <string>

using namespace std;

struct Command {
    string  name;
    int     value = 0;
    vector<string> instructions;

    friend ostream& operator<<(ostream& os, const Command& c) {
        return os << "Name: " << c.name
            << "\nValue: " << c.value
            << "\nInstructions: " << c.instructions.size();
    }
};

using Commands = std::vector<Command>;

int main(int argc, char** argv)
{
    Commands commands;

    CLI::App app;

    app.set_config("--conf,-c");

    Command cmd;

    auto command_app = app.add_subcommand("subcommand", "Subcommands")
        ->immediate_callback(true)
        ->configurable(true)
        ->preparse_callback([](size_t s) {
        cout << "-----   preparse callback: " << s << endl;
    })
        ->parse_complete_callback([&]() {
        cout << "-----   parse complete callback " << endl;
        commands.push_back(cmd);
        cmd = {};
    });

    command_app->add_option("--name",
        cmd.name,
        "Name")->mandatory();

    command_app->add_option("--value",
        cmd.value,
        "Value")->default_val(1);

    command_app->add_option_function<int>("--count",
        [&](const auto& v) {
        cmd.instructions.resize(v);
    }, "Count");

    CLI11_PARSE(app, argc, argv);

    for (auto&& c : commands)
        cout << "-----\n" << c << "\n";
}
```
the associated configuration file:
```
[subcommand]
name = NAME1
#value = 1   # default value

[subcommand]
name = NAME2
count = 1
value = 5

[subcommand]
name = NAME3
count = 2
value = 3

[subcommand]
name = NAME4
count = 10
```

I expect to be a symmetry between parse_complete_callback and preparse_callback.
Do I do something something wrong ? or is there a better way to load multiple section from an  ini file ?
The aim is to remove the temporary cmd, et replace it by a push_back to commands on preparse call.
Regards,

**Comment by dfleury2** [comment]
I have made an attempt to see how it could be done.
In CLI11.hpp, in _trigger_pre_parse, I have added
```cpp
        ...
        } else if(immediate_callback_) {
            if (always_call_pre_parse_callback_ && pre_parse_callback_) {
                pre_parse_callback_(remaining_args);
            }

            if(!name_.empty()) {
            ...
```
and a default param to preparse_callback (lambda, bool always_called = false).
It works as expected for my sample.
You have more knowledge on CLI11, to improve and see what can be done.

**Comment by phlptp** [comment]
The original use cases for pre-parse callback was for doing some global setup for the subcommand, or for allowing some modifications to the argument processing depending on the number of inputs entered.  

It looks like in your case that is a use case for the preparse callback that has not been dealt with.  

There also has been some discussion about adding a 4th callback which would occur after parsing but prior to option callbacks being executed.

**Comment by dfleury2** [comment]
Ok, He see not exactly my use case.
I will live with it this way, until something change in the API taht help me.
Thanks.
