### ISSUE TITLE
how to make a read–eval–print loop (REPL) shell

### ISSUE THREAD

**Issue by itviewer** [CLIUtils/CLI11#464]
Hi,
I want to know how to achieve the function like a REPL:
If the user does not enter any parameters, enter an interactive shell, then the user can enter some commands, we do something, until the user enters the `quit` command, then program exit.
Thanks.

**Comment by phlptp** [comment]
https://github.com/GMLC-TDC/HELICS/blob/master/src/helics/apps/helics-broker.cpp  is an example of a terminal like program using CLI that we are using.  
if you wanted the terminal to start if there were no arguments then I would probably do something like
```
bool startTerm{false};
app.pre_parse_callback([&]{size_t N){startTerm=(N==0);});
...

```

**Comment by wolfv** [comment]
Hi @itviewer you can check out @certik terminal, it includes an example for a REPL: https://github.com/certik/terminal

**Comment by itviewer** [comment]
@wolfv thanks

**Comment by certik** [comment]
@itviewer and others, if you want to collaborate on https://github.com/certik/terminal, let me know. I'll be using it in [LFortran](https://lfortran.org/) very soon.
