### ISSUE TITLE
MSVC 16.6.0 removes std::result_of with /std:c++latest

### ISSUE THREAD

**Issue by steffenb7333** [CLIUtils/CLI11#465]
Using /std::c++latest with the current version of Visual Studio 2019 causes `std::result_of` not to be defined anymore and App.hpp to fail compilation.

Quick-fix is to comment out `struct detail::AppFriend` at the end of the header.

**Comment by phlptp** [comment]
I think this was fixed in #459.  You will need to use master vs 1.9

**Comment by steffenb7333** [comment]
Confirmed, it does work then.

Are there any plans for a 1.9.1 release?

**Comment by phlptp** [comment]
I think the next release was planned to be a 2.0,  but I am not sure where things stand right now or what a timeline for that might be.  We probably should add a note about the latest visual studio and /std::c++latest though.

**Comment by henryiii** [comment]
I am rather suspecting we will need a 1.9.1. There are several fixes (like the one above) that probably should be deployed before 2.0 is out, and 2.0 will be a more disruptive upgrade.

**Comment by henryiii** [comment]
The logic in #459 seems be breaking in the windows-latest builds.

**Comment by henryiii** [comment]
This should be backported into the v1 branch now. I think we will make a v1.9.1 release from the v1 branch soon. Feel free to test and verify v1 also works!

**Comment by henryiii** [comment]
Tagged v1.9.1, which should include the fix!
