### ISSUE TITLE
CLI11 does not compile without rtti

### ISSUE THREAD

**Issue by certik** [CLIUtils/CLI11#466]
My project is compiled without rtti. I get the following error when trying to use CLI11 version 1.9.0:
```
.../src/bin/CLI11.hpp: In member function ‘int CLI::App::exit(const CLI::Error&, std::ostream&, std::ostream&) const’:
.../src/bin/CLI11.hpp:5863:54: error: ‘dynamic_cast’ not permitted with -fno-rtti
         if(dynamic_cast<const CLI::RuntimeError *>(&e) != nullptr)
                                                      ^
```
Is RTTI required to use CLI11?

**Comment by henryiii** [comment]
Error catching is currently required. One project for 2.0 is making error catching optional. That would change app.exit, and I don't think RTTI will be used anymore there.

However, I'm not sure how heavily RTTI is required other than in error catching, and then only in app.exit. You could implement that without it fairly easily, I think.

It is also used for needs/excludes, ignore_case, and ignore_underscore. For those, though, I don't think it's required, it's just a bit safer than a stronger cast (and you you can avoid those methods for now).

**Comment by henryiii** [comment]
Dumb question; can you split up error catching by subclass when RTTI is off?

**Comment by certik** [comment]
@henryiii the #467 fixes it for me. Now I can use CLI11 in my project.

I can see couple options. Do some ifdefs and support both approaches, or just use the approach in #467. I am not an expert in C++, but isn't it recommended to try to avoid using `dynamic_cast`?

**Comment by henryiii** [comment]
The approach there is fine, though I might consider adding a bool or int property that we can check instead of a string (that will also allow those to be subclassed, just in case someone does). Avoiding `dynamic_cast` is preferable, yes.

**Comment by certik** [comment]
Yes, I was going to add some int or bool, but then just did a string comparison, as it was easier. In my other C++ projects I typically use some enum / int.
