### ISSUE TITLE
Display of subcommands in Help

### ISSUE THREAD

**Issue by patlecat** [CLIUtils/CLI11#468]
I added subcommands and options below it and i get them by using `app.get_subcommands()` but those sub-options do not appear in the help list at all. Why not? I don't control the help page, the lib does.

```
auto dom_def = m_conf.add_subcommand("dom_def",  "The default parameters ...");
auto domain = dom_def ->add_option("--domain", this->domain, "Enter domain ...");
 ```

**Comment by henryiii** [comment]
Do you want `--help-all`?

**Comment by henryiii** [comment]
You can set help-all to `-h,--help` and remove the normal help, if that's what you want for your users. But I think help-all is what you want. You can do `./program dom-def --help` to get subcommand help normally.

**Comment by patlecat** [comment]
Yeah a help showing all commands and subcommands would be kind of normal to show.

**Comment by henryiii** [comment]
If you find it useful for your application, you can do:

```cpp
m_conf.set_help_flag(); // Remove help flag
m_conf.set_help_all_flag("-h,--help", "Print this help message and exit");
```

Now you only have `--help` which triggers help-all. For a large application, it is much more common to hide subcommand options, and only show them per-subcommand or with `--help-all`.
