### ISSUE TITLE
Error during CMake on Win10 + VS14

### ISSUE THREAD

**Issue by CyrilShch** [CLIUtils/CLI11#478]
Has anyone experienced the problem during CMake procedure?

![image](https://user-images.githubusercontent.com/50148272/84587693-291f5480-ae2a-11ea-825b-b324e717510e.png)

Specifically, the error occurs in this CMakeList.txt line:
![image](https://user-images.githubusercontent.com/50148272/84587736-86b3a100-ae2a-11ea-9903-6b249cc4eadb.png)

**Comment by henryiii** [comment]
Yes, in #457; can you see if #471 fixes it? It's the one thing I'm waiting on before releasing 1.9.1. I don't use Windows so can't easily test it.

**Comment by henryiii** [comment]
Edit: Corrected link to PR above.

**Comment by henryiii** [comment]
Edit: Someone did test it and I missed it. I'll update, don't bother to test until I do.

**Comment by henryiii** [comment]
Should be fixed, just tagged v1.9.1 which includes the fix!
