### ISSUE TITLE
Parsing positionals after '--'

### ISSUE THREAD

**Issue by alinalihassan** [CLIUtils/CLI11#480]
I want to achieve a similar style to Rust's cargo, where in cargo run, '--' is used to delimit cargo arguments from the program's arguments. Is this possible to mimic that behavior here? It doesn't allow me to simply define "--" as an option.

Eg. cargo run --some-flag -- any arguments here --main-func-flag

**Comment by henryiii** [comment]
Just try it with `app.allow_extras()` and `app.remaining()`; `--` is already supported. You might want to try the special `prefix_command` mode as well. (see https://github.com/CLIUtils/CLI11#subcommand-options)

**Comment by alinalihassan** [comment]
I am able to allow extras using the app but not limit it to certain subcommands, is this intentional?

**Comment by henryiii** [comment]
Can you post an example? Remember that subcommands inherit the settings of the parent at the point they were created, so if you set something on the main app *before* adding the subcommand, they will get it too. Anything marked with an INHERITABLE here: https://cliutils.github.io/CLI11/class_c_l_i_1_1_app.html#ae994679fee098b93cbc654a99b8019ee
