### ISSUE TITLE
Parse data separated with --

### ISSUE THREAD

**Issue by carlos-granados** [CLIUtils/CLI11#481]
I need to parse commands given in the following format:

command [options] [-- data]

Where options is a list of options in the format -n value and data is an optional base64 encoded string

For example

set -i 1 -n name -- abcdef01234

Is it possible to parse these commands using CL11 (specifically not sure how to implement the -- data part)

**Comment by henryiii** [comment]
The `--` already ends options, you'll just need to enable extras with `app.allow_extras()` and then access `app.remaining()` to get the items that come after the `--`.

**Comment by henryiii** [comment]
You can also use a vector-based unlimited argument here, I believe - would have to check to see if it handles `--` the same way.

**Comment by carlos-granados** [comment]
Thanks, I had not thought that I could use `allow_extra()` for this. Works perfectly
