### ISSUE TITLE
[support] Can Cli11 add custom descriptions ?

### ISSUE THREAD

**Issue by woshidama323** [CLIUtils/CLI11#483]
Can Cli11 add custom descriptions ?
For example like this ?

```shell
Example:
    sendtx transfer zX9SuJhRuhM9bCs5sM
```

**Comment by henryiii** [comment]
Where do you want to put it? Yes, in most places. There's a description for the top, a footer for the bottom, a custom "type" (just after the name), and of course, the help text. And if that's really not enough, there's a custom help formatter system.

**Comment by woshidama323** [comment]
Thanks for your comments. say, I want to add an example on a subcommand 

```shell
./cli subcommand

Params:
  account_addr ...
  amount .....

Options:
   -h,--help Show 
   --note STRING 
   --tx_deposit STRING Transaction

Example:
    sendtx transfer bX1aXzX9SuJhRuhM9bCs5sM
```  

could you help to tell where I can find an example? Thanks

**Comment by henryiii** [comment]
That's a footer on a subcommand. `->footer(...)`, where ... is your custom text.

**Comment by woshidama323** [comment]
Got it ,Thank you so much

**Comment by woshidama323** [comment]
Hi, I just use header file in my program

I noted that set_footer has been changed to footer in the version below?

```shell
// CLI11: Version 1.9.0
// Originally designed by Henry Schreiner
// https://github.com/CLIUtils/CLI11
```

**Comment by henryiii** [comment]
Sorry, in 1.5-1.6 this was normalized for consistency. I gave the old name out of habit.

**Comment by woshidama323** [comment]
> Sorry, in 1.5-1.6 this was normalized for consistency. I gave the old name out of habit.
