### ISSUE TITLE
Ability to leave unknown options for later parsing

### ISSUE THREAD

**Issue by eyalroz** [CLIUtils/CLI11#485]
CLI11 insists on only encountering recognized options; and, at most, is willing to invoke a callback to handle unrecognized ones. But - what if I just want to get those options, to do something with them myself? Preferably, as a map + a set (of flags) + a vector (of positionals); or at worst as an extra, residual command-line?

I should mention Boost program_options has this ability.

**Comment by phlptp** [comment]
CLI supports and `allow_extras()` option on  the main app for parsing.  this allows later retrieval through `remaining()`  or `remaining_for_passthrough()`
