### ISSUE TITLE
Providing several config files

### ISSUE THREAD

**Issue by jbriales** [CLIUtils/CLI11#486]
I read through the docs but didn't found anything about this:
Would it be possible in CLI11 to take several input config files, and just concatenate their entries?
Currently if I provide `--config` more than once I just get:
> --config: At Most 1 required but received 2

The motivation would be to be able to reuse multiple subsets of options and combine them.

**Comment by phlptp** [comment]
I don't think it is currently handled but I don't think the modification would be that hard.
