### ISSUE TITLE
More convenient type deduction for parameters

### ISSUE THREAD

**Issue by ulfllorenz** [CLIUtils/CLI11#492]
Currently, when I want some type safety, I have to write something like that:

`
int myParameter;
myApp.add_option("--foo", myParameter, "");
`

This is a bit annoying, because I have to write two lines of code instead of one; in general, I would prefer to use the option directly, but as far as I understand, this is the syntax needed to get CLI11 to do the cast checking. Is there a concise alternative solution possible, at least for simple (numeric) types; maybe an obvious extension would be user-defined types with a certain notion of well-behaved.

As a related issue, and possibly a solution, the various number checkers are not typed. For example, CLI11::PositiveNumber reads in an argument as a double, but I happen to require an int. So in addition, it would be nice to have the various checkers typed properly, maybe even have a type checker to skip the explicit adding of a variable reference.

**Comment by phlptp** [comment]
I think this has been addressed with the addition of the type validator.  So I am going to close it.
