### ISSUE TITLE
How do I set format string based on my custom type

### ISSUE THREAD

**Issue by pavelgeiger** [CLIUtils/CLI11#495]
Hi, I have option which assigns to my own type Foo. In the help output it is shown as type INT, because Foo is assignable from int.
I would like to be able to say, hey if I have this type Foo, show it always as BAR in the help output. I have tried messing with type_name overloads in CLI::detail namespace but with no success. Is there any way, how to do it? Same thing is with defaults. I would like to have my own custom default printer for my Foo. Thanks

**Comment by phlptp** [comment]
I think what you want to update is 
```
->type_name(typename): Set the name of an Option's type (type_name_fn allows a function instead)
```

`opt->type_name("BAR")` should override the default INT value

**Comment by pavelgeiger** [comment]
Thank you for response. I know about this option, but it isn't exactly what I want. I would like to have specified type name for given type at one place, so I do not need to think about types when adding options.

**Comment by phlptp** [comment]
I think I understand now.  This is what we do for that in one of the projects I use CLI11 in quite a bit

```C++
// use the CLI lexical cast function overload to convert a string into a time
namespace CLI {
namespace detail {
    template<>
    inline bool lexical_cast<helics::Time>(const std::string& input, helics::Time& output)
    {
        try {
            output = loadTimeFromString(input, time_units::ms);
        }
        catch (std::invalid_argument&) {
            return false;
        }
        return true;
    }

    template<>
    constexpr const char* type_name<helics::Time>()
    {
        return "TIME";
    }
}  // namespace detail
```

The whole file is [here](https://github.com/GMLC-TDC/HELICS/blob/master/src/helics/core/helicsCLI11.hpp)

**Comment by pavelgeiger** [comment]
That was it! Thank you very much!
