### ISSUE TITLE
Install instructions CMake

### ISSUE THREAD

**Issue by ferdymercury** [CLIUtils/CLI11#498]
I use CLI11 in many small independent projects (folders). Thus, I was trying to install it as a shared folder accessible by other users, for example /opt/CLI11

Then, in my projects, I do:
`find_package(CLI11 CONFIG REQUIRED)`
as suggested in the Readme, specifying the proper CLI11_DIR path.

However, I get the following error:
`CLI11Config.cmake not found.`

If I check the build directory, only the following exist:
`CLI11ConfigVersion.cmake  CLI11Targets.cmake  CMakeDoxygenDefaults.cmake  cmake_install.cmake  CPackConfig.cmake  CPackSourceConfig.cmake  CTestCustom.cmake`

Am I doing something wrong? (I think the README.md is a bit unspecific in this respect.)

**Comment by ferdymercury** [comment]
A workaround could be to use:

```
# Add CLI
if(NOT DEFINED CLI11_DIR)
set (CLI11_DIR "/opt/CLI11" CACHE STRING "CLI11 git repository")
endif()
include_directories(${CLI11_DIR}/include)
```

And then include at least the following:
```
#include "CLI/App.hpp"
#include "CLI/Formatter.hpp"
#include "CLI/Config.hpp"
```

**Comment by jzakrzewski** [comment]
Judging from the files you see, you've pointed it to a build directory instead of install directory.

**Comment by ferdymercury** [comment]
Thanks for the hint and quick reply! Yes, it was the build directory.

But I thought 'installing' was 'optional', according to the README:

`You can also configure and optionally install the project, and then use find_package(CLI11 CONFIG) to get the CLI11::CLI11 target.`

I thought building it would have been enough. Maybe this sentence can be reworded a bit?

Anyway, now it works.

**Comment by jzakrzewski** [comment]
Yes, it's optional but then you don't get the CLI11::CLI11 target and cannot use find_package(). In short you have these options:
1. copy CLI11.hpp to your project and use as you wish
2. add the location of CLI11/CLI11.hpp to header search path (this can be the location inside cloned CLI11 git repo so you can keep it centralized and up-to-date)
3. add CLI11 to your project as subdirectory - use `add_subdirectory()` and use `CLI11::CLI11` target
4. install CLI11  - use `find_package()` and use `CLI11::CLI11` target

If that wasn't clear to you, maybe you could propose a more clear wording for the "Install" part of the readme? I'm sure the maintainers will appreciate it.

**Comment by ferdymercury** [comment]
thanks!

and maybe a variation of 2:

5.` include_directories(${CLI11_DIR}/include)` in your CMakeLists and then use `#include "CLI/App.hpp"` etc. in the source code.

I will open a PR
