### ISSUE TITLE
Type deduction on std::optional<uint64_t> doesn't work as expected

### ISSUE THREAD

**Issue by max-ag** [CLIUtils/CLI11#501]
The classification of std::optional<uint64_t> isn't the same as the classification of uint64_t.
I didn't test with other types wrapped in std::optional.

```
classify_object<std::optional<uint64_t>>::value -> object_category::number_constructible
classify_object<uint64_t>::value -> object_category::unsigned_integral
```

The result is a double->uint64_t narrowing conversion happening (and generating a warning) when adding an option to an app.

I believe the problem comes form `is_direct_constructible`, which returns true for `std::optional<uint64_t>`, and false for `uint64_t`.

I'm using Visual Studio 2019 (v16.7.0)

**Comment by phlptp** [comment]
I will take a look, thanks.

**Comment by phlptp** [comment]
I can't replicate this issue in current master branch.  Possibly an issue in the previous release, but either way seems fixed now.
I added a test in PR #542
