### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by asurada404** [CLIUtils/CLI11#502]
I use the [5th method](https://github.com/CLIUtils/CLI11/blob/master/README.md#install) to install [CLI11](https://github.com/CLIUtils/CLI11).

I test the [`../CLI11/test_package`](https://github.com/CLIUtils/CLI11/tree/master/test_package) and want to use `find_package` to include `CLI11` but failed.

The content of CMakeLists.txt.
```
project(PackageTest CXX)
cmake_minimum_required(VERSION 3.1)

find_package(CLI11 CONFIG REQUIRED)
...

```
I got the error as follow:
```
CMake Error at CMakeLists.txt:6 (find_package):
  Could not find a package configuration file provided by "CLI11" with any of
  the following names:

    CLI11Config.cmake
    cli11-config.cmake

  Add the installation prefix of "CLI11" to CMAKE_PREFIX_PATH or set
  "CLI11_DIR" to a directory containing one of the above files.  If "CLI11"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
...
```

**Comment by henryiii** [comment]
Where did you install to? If you install to some place like `/usr/local`, it should get picked up automatically by CMake, but if not, you need to set `CLI11_DIR` to the install path.

**Comment by asurada404** [comment]
Thanks for your hints and reply so quickly. 
I didn't execute `make install` before. 
I solved this problem by the following steps.
Step1. install CLI11
```
mkdir build
cd build
cmake ..
make 
make DESTDIR=/home/xxx/CLI11_INSTALL install 
```
Step2. configure the path of CLI11
cmake test_package with `DCMAKE_PREFIX_PATH` to configure the path of CLI11.
```
cmake -DCMAKE_PREFIX_PATH=/home/xxx/CLI11_INSTALL/usr/local/ ..
```
