### ISSUE TITLE
Formatting positional default string

### ISSUE THREAD

**Issue by mbhall88** [CLIUtils/CLI11#505]
I know how to format the default string for optionals, but am struggling to get the desired result for positionals.

For example, I have the following,

```c++
CLI::App app{"..."};
auto sub = app.add_subcommand(
    "sub", "Subcommand.");
std::string infile;
sub->add_option("infile", infile, "input file")
    ->required()
    ->check(CLI::ExistingFile);
int rand_opt{0};
index->add_option("-o", rand_opt, "random option")
    ->type_name("INT")
    ->capture_default_str();
// other code
```
which produces

```
...
Usage: ./app sub [OPTIONS] infile

Positionals:
  infile TEXT:FILE REQUIRED      input file

Options:
  -h,--help                   Print this help message and exit
  -o INT=0                    random option

```

What I would like to do is format the `TEXT:FILE` part to just say `FILE`. Using `type_name("FILE")` just returns `FILE:FILE`. So effectively, what I need to know if how to get rid of the `:FILE` part.

**Comment by phlptp** [comment]
The `:FILE` comes from the `->check(CLI::ExistingFile)`  Simplest might be to just use type_name("")  though I am not sure if it would still put the ':' or not.   Otherwise you can modify the `Validator` to adjust the string in that object.

**Comment by mbhall88** [comment]
> The `:FILE` comes from the `->check(CLI::ExistingFile)` Simplest might be to just use type_name("") though I am not sure if it would still put the ':' or not. Otherwise, you can modify the `Validator` to adjust the string in that object.

I tried that but it did leave the colon in there still, so it left `:FILE`. 

Ok, I managed to get it to work by digging around based on your suggestion. For anyone else, I deleted lines 4433-4435 in the `CLI11.hpp` release (version 1.9.1), which is in the function `Option::get_type_name`. It basically removes the section that adds `:<Validator type>`

**Comment by phlptp** [comment]
```
CLI::App app{"..."};
auto sub = app.add_subcommand(
    "sub", "Subcommand.");
std::string infile;
sub->add_option("infile", infile, "input file")
    ->required()
    ->check(CLI::ExistingFile.description(""));
int rand_opt{0};
index->add_option("-o", rand_opt, "random option")
    ->type_name("INT")
    ->capture_default_str();
// other code
```

I think you can do a similar thing by just making the description return an empty string.

**Comment by mbhall88** [comment]
Yep! That's a much nicer solution.
