### ISSUE TITLE
Show value passed for failing `isMember` validation.

### ISSUE THREAD

**Issue by Dr-ZeeD** [CLIUtils/CLI11#515]
Currently, when the membership check fails and CLI11 reports the error, the actual value is not shown but only ` not in {...}`.
Change should be here, I guess. I can open a pull request in the upcoming days when I'm on a machine with git.

https://github.com/CLIUtils/CLI11/blob/c1666528ef0b1b5ddeacc60fba0f01f67cc7c7e8/include/CLI/Validators.hpp#L749

**Comment by henryiii** [comment]
@allcontributors please add @ZeeD26 for code
