### ISSUE TITLE
Help subcommand 

### ISSUE THREAD

**Issue by Leon0402** [CLIUtils/CLI11#522]
Hi, 

I was wondering if it's currently possible to add a help subcommand rather than a help flag (or in addition to it). Manually adding it doesn't work: 

```
auto helpCommand = parser.add_subcommand("help", "Shows the help-page");
helpCommand->callback([this]() {
    std::cout << this->parser.help();
});
```
This will execute basically `Program help --help`, so the help menu of the subcommand help. 

To give a prominent example, where such an approach is used: git 
Instead of `git --help` you can execute `git help`. 

It would be nice if this help subcommand worked in the same way as the flag, so: 
`Program subcommand --help` could be written as `Program help subcommand`
Git doesn't offer this feature, but something similar. You can for instance get more detailed information on a topic (and not on a subcommand) for instance `git help workflow`, while `git help commit` doesn't work. Providing this option as well might be interesting as well, but I personally don't need it and I guess this would require more effort to implement as well. 

Thanks!

**Comment by phlptp** [comment]
I don't know why this wouldn't work,  what goes wrong with the code above?    When using it like that you will need to make sure the lifetime of the this pointer at least matches that of the parser that is executing the parse.  

If you just wanted it to behave exactly like call for help I would probably just do
```
auto helpCommand = parser.add_subcommand("help", "Shows the help-page");
helpCommand->callback([]() {
    throw CLI::CallForHelp();
});
```

or even 
```
auto helpCommand = parser.add_subcommand("help", "Shows the help-page");
helpCommand->preparse_callback([](std::size_t /*unused*/) {
    throw CLI::CallForHelp();
});
```

which will short circuit any further processing.

Then CLI11_PARSE will work identically to the --help built in function

**Comment by Leon0402** [comment]
Hi, 

thanks for the comment! As I said, it doesn't work (at least the way I do it), because it's inside a subcommand.

Imagine what would happen if you call "MyApp subcommand --help". It wouldn't show the complete help menu, but just the part relevant parts for that subcommand.
The same happens here. The command "MyApp help" is "translated "to ""MyApp help --help" rather than just "MyApp --help". 

The output is: 
```
Shows the help-page
Usage: MyProgramm [OPTIONS]

Options:
  -h,--help                   Print this help message and exit
```
So as you can see it shows above the "Usage" part the message of the help subcommand rather than the description. And it also doesn't show any subcommand (which is exactly what happens if you call "MyProgram subcommand --help"))

In contrast when I just use `parser.help()` in the main.cpp somehwere (so not inside the callback from the subcommand), the help menu is completly shown.

> Then CLI11_PARSE will work identically to the --help built in function

I think this is exactly the point. It will work identically. So if you call --help on the subcommand, a specific help menu for that subcommand will be shown. And the same happend here I assume.

**Comment by phlptp** [comment]
Ahh, I see now.

Presuming you don't actually care about any other parsing that was going on
```c++
auto helpCommand = parser.add_subcommand("help", "Shows the help-page");
helpCommand->callback([this]() {
    this->parser.clear();   //This will remove the subcommand from the selected list and anything else that was going on.  
    std::cout << this->parser.help();
});
```

**Comment by phlptp** [comment]
Looking at it though it might make sense to have an overload of the help operation that didn't dive into the subcommands.

**Comment by Leon0402** [comment]
Thanks! That works for what I was trying to achieve.

But I agree that it would be cool if the help subcommand would be not treated as a subcommand, but literally transpiled to a --help flag. This would allow scenerarios such as: 
`MyProgramm help subcommand`

Which is imo in a terminal application, which strongly uses subcommands, more intuitive than the help flag. 

So possibly just a method like addHelpSubcommand()   which adds this special rule automatically.

**Comment by Leon0402** [comment]
So I found a nice way to make this work with the current features

```cpp
    auto helpCommand = parser.add_subcommand("help", "Prints this help message");
    static std::string helpSubcommand = "";
    helpCommand->add_option("subcommand", helpSubcommand, "Get help for this subcommand");
    helpCommand->callback([&]() {
        if(helpSubcommand.empty()){
            parser.clear();
            throw CLI::CallForHelp();
        } 
        
        std::cout << parser.get_subcommand(helpSubcommand)->help();
    });
    parser.set_help_flag("-h,--help", "Prints this help message");
```
This will allow `MyProgramm help someSubcommand`. 

One general question. Is there a better / alternative way to have the option "helpSubcommand" available in the helpCommand callback? I don't like that helpSubcommand is static here (otherwise it will be out of scope).
The docs list something like I can use "results()" to get the option from the parser. But I wasn't able to make it work.

**Comment by phlptp** [comment]
This can be done easily now with 

```
auto sub1 = app.add_subcommand("help")->silent();
    sub1->parse_complete_callback([]() { throw CLI::CallForHelp(); });
```
