### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jwinarske** [CLIUtils/CLI11#535]
Would you consider changing to boost licensing?

**Comment by henryiii** [comment]
Only if this was added to Boost. :) It already has a permissive license, which I had to fight for (UC wanted LGPL, IIRC).

**Comment by jwinarske** [comment]
Okay.  Appreciate the thought.

**Comment by henryiii** [comment]
For my own information, is there a reason you liked Boost better?

**Comment by jwinarske** [comment]
Boost is commercial friendly.  Aside from boost having program_options, Poco also has an options parser.  Both boost licensed.

**Comment by henryiii** [comment]
BSD 3-clause is commercial friendly, too. The only difference I'm aware of is you have to include the license somewhere with most licenses, but not Boost. If you have an iPhone, you can go to Settings -> General -> Legal & Regulatory -> Legal Notices and you'll see a list of licenses that Apple used in making iOS, like MIT & BSD. It's explicitly business friendly - they don't have to provide the source. While GPL / LGPL are not.
