### ISSUE TITLE
Same add_option_func option used multiple times?

### ISSUE THREAD

**Issue by mcelhennyi** [CLIUtils/CLI11#538]
Can I reuse the options in any order after a subcommand?

-------------------------------------------------------------------------------------------------------------------------------------------------------

I have the following scenario:

I have a subcommand called `action` that has the following options:

`            actionCommands->add_option_function<float>(
                    "-f, --float",
                    std::bind(&CLIParser::argValueSet<float>, this, std::placeholders::_1),
                    "The arguments type/value")`
`            actionCommands->add_option_function<int>(
                    "-i, --int",
                    std::bind(&CLIParser::argValueSet<int>, this, std::placeholders::_1),
                    "The arguments type/value")`

I would like to be able to do the following:
`action -i 1 -f 2 -f 4 -f 3 -i 9 -i 2`

This should result in the argValueSet function being called with each item. The current result is that only the first two work (if I set multi_option_policy(CLI::MultiOptionPolicy::TakeFirst or TakeAll, otherwise it throws an exception about having too many args).

argValueSet fills an array with boost::any values for each of the options on my command. These array values are eventually used to call a function of variable input arguments. So I need a way of signifying the type and being able to have any number of args with specified types to follow.

Any ideas?

**Comment by phlptp** [comment]
the option callbacks are only executed once so you are only getting a single value returned.

You have the callback take a vector<TYPE>  that will get them all or use some variation of the `each` operation which will be executed for each argument but you would need to do the parsing.  

personally I would use a vector version of the callback and wrap your call in a lambda operation.

**Comment by phlptp** [comment]
I think with the recent releases another option is to use ->trigger_on_parse(true) modifier on the option.  This will execute the callback each time the argument is passed.

**Comment by phlptp** [comment]
Unless there are some additional questions I think this issue can be closed, now that `trigger_on_parse` is available

**Comment by mcelhennyi** [comment]
@phlptp That is fine, I can reopen when I get around to it if this does not suffice. I built some work arounds so I do not *need* this feature as of now.
