### ISSUE TITLE
config_to_str does not reflect changed options

### ISSUE THREAD

**Issue by StarGate01** [CLIUtils/CLI11#539]
When using the function `config_to_str`, the values of the options are those from the initial parsing.

Is there any way to change values of the options during runtime after parsing, and have the generated config file reflect those changes? Case in point: User edits settings in UI, new settings are then to be saved to the config file.

Thank you for any help.

**Comment by andioz** [comment]
Hi, I'm currently investigating a different problem with config_to_str(), just stumbled into your issue. For me it looks like you want to use the `CLI::App class` as a sort of configuration storage during the whole lifetime of your application? If it is like that, I would recommend: don't do that. As far as I know different parsers, their goal is to `parse` config lines (and configuration files). And nothing more. After parsing, the instance is consumed, maybe like an iterator after reaching the end. I would use normal data structures for configurations instead.

Another point for from my experiences in general is, not to use specialized libraries all over the place in your application, this will lead into some kind of dependency hell. Restrict the usage of CLI for parsing arguments (and saving changed configurations to files if required), don't use database library structures outside the DB connectivity parts, don't use Google ProtocolBuffers as your first class data structures (I thing Google mentions this in their documentation?), etc. I'm not inventing this, you can read this for example in the great books from Robert C. Martin.

Sorry for not showing a solution, but I think to redesign will keep you away from further trouble.

**Comment by StarGate01** [comment]
Thank you for your answer.

I see your point, that was about what I was expecting. Although I do not use CLI11 as configuration storage, I was hoping to use it as a configuration serializer, so that I do not have to add a dependency for INI file generation.

However, I will take your advice, and keep using CLI11 strictly for parsing.

**Comment by andioz** [comment]
If you are looking for a INI file serializer/deserializer only, maybe you can find another lib for that. I just found https://github.com/benhoyt/inih or https://github.com/mcmtroffaes/inipp, but there must be more. I'm thinking about combining CLI11 with one of these within a custom Config instance.

**Comment by StarGate01** [comment]
For my use-case, serializing would be sufficient. As the INI format (for my project) is fairly simple, I will probably implement it by myself. Great idea with the custom Config instance, ideally I would arrive at a system which internally handles both CLI11 and settings storage / serialization.
