### ISSUE TITLE
Config representation of default value for functor flags is incorrect

### ISSUE THREAD

**Issue by eddyashton** [CLIUtils/CLI11#540]
I have a flag which should trigger a functor when it is present:

```c++
void print_version(size_t) { ... }

...

app.add_flag("--version", print_version);
```

If I try to produce a config of this, with `default_also = true`, then it will insert a line `version=false`. If I try to use this config, the presence of `version` (regardless of the assignment, even if it were a line containing only `version`) triggers the functor - when parsing the config, the flag is present. So the config does not describe the same arguments that were passed to the current instance, and cannot be used to rerun this instance.

I don't know enough about the internals to fix this, but believe either the config parser should recognise `version=false` in this instance, or this should be serialised into the config as `; version` (ie - commented out).

Here's a minimal repro example:
```c++
#include <CLI11/CLI11.hpp>
#include <fstream>
#include <iostream>

void print_version(size_t)
{
  std::cout << "Version is 42" << std::endl;
  exit(0);
}

int main(int argc, char** argv)
{
  CLI::App app{"repro"};
  app.set_config("--config", "", "Read config", false);
  app.allow_config_extras(false);

  app.add_flag("--version", print_version);

  CLI11_PARSE(app, argc, argv);

  std::cout << "Reached end of main!" << std::endl;
  const auto config_file = "./config.ini";
  std::cout << "Writing config to " << config_file << std::endl;
  std::fstream fs;
  fs.open(config_file, std::fstream::out | std::fstream::trunc);
  fs << app.config_to_str(true, false);
  fs.close();

  return 0;
}
```

```
$ ./a.out 
 Reached end of main!
 Writing config to ./config.ini
$ cat ./config.ini 
 version=false
$ ./a.out --config ./config.ini
 Version is 42
```

**Comment by phlptp** [comment]
That callback returns a value in the size_t argument.  It will get called with a value <=0 if the value is false and was passed.  
So in that case you would be needing to check the argument.

there is also an add_flag_callback which will only execute if true which might be what you want in this case

**Comment by eddyashton** [comment]
Ah ha, `add_flag_callback` is exactly what I was looking for, thanks!
