### ISSUE TITLE
config_to_str does not work for tuple

### ISSUE THREAD

**Issue by pwm1234-sri** [CLIUtils/CLI11#550]
I have an option that is a ``std::tuple<double, double, double, double>`` type. 
When I call ``App::config_to_str`` the tuple option is not being written to the config string because its string representation is empty.
I am, however, able to use the option in the config file, so I know the to/from string steps are working everywhere except in ``config_to_str``.

I am using 1.9.0 and I see that 1.9.1 has a string conversion fix, #421, but I do not know if that fix also addresses tuple problems like this.

Thanks for make CLI11 a great library for the rest of us to use! (I have bugged you in the past from account @pwm1234)
Phil

**Comment by phlptp** [comment]
I added a test 
```
std::tuple<double, double,double,double> t;
    app.add_option("--tuple", t);
    app.config_formatter(std::make_shared<CLI::ConfigTOML>());
    args = {"--tuple", "1", "2", "3", "4"};

    run();

    std::string str = app.config_to_str();
    CHECK(str == "tuple=[1, 2, 3, 4]\n");
```

as best as I can tell this should be working in the current release, so unless there is a specific further issue, I think this can be closed.

**Comment by pwm1234-sri** [comment]
Let's close it then. I will re-open if I encounter problems.
