### ISSUE TITLE
Support for implicit values?

### ISSUE THREAD

**Issue by Psalm27-4** [CLIUtils/CLI11#555]
Is there support for implicit values? I've seen in other frameworks something like this (converted to this parser's API):

`
std::string name;
app.add_option("-f,--file", name, "The filename")->default_value("default.txt")->implicit_value("other.txt");
`
If the option is not supplied on the command line, name gets set to default.txt. If the option is specified on the command line, but without a value, name is implicitly set to "other.txt". Finally, if the option is given a value, it gets set to that.

Is something like this possible?

**Comment by phlptp** [comment]
Only for `add_flag`

```
std::string name; 
app.add_flag("-f{other.txt},--file{other.txt}", name, "The filename")->default_value("default.txt")->run_callback_for_default();
```
This will set name to "default.txt" for no option given
'-f'  will result in name being assigned other.txt
--file="yet_another_file.txt"  will result name being assigned "yet_another_file.txt"

**Comment by phlptp** [comment]
One addition is you can change the expected number of values to ->expected(0,1)  then it would behave like a regular option

so 
```
std::string name; 
app.add_flag("-f{other.txt},--file{other.txt}", name, "The filename")->default_value("default.txt")->force_callback()->expected(0,1);
```

this would assign other.txt if  -f was called with no argument,  and would assign default.txt if no flag was used at all.
