### ISSUE TITLE
How to not require an argument?

### ISSUE THREAD

**Issue by InformatikerImAll** [CLIUtils/CLI11#557]
uint32_t inodes = 1000;  // my default value
    CLI::Option *m = app.add_option("-m, --mkfs", inodes, "Create Image: default is 1000 inodes."); 
  

if I try to run this like: ./hbfs -m 

it requires 1 argument. But I want the argument to be optional, otherwise 1000 should be default.
How can I do that?
btw. thx a lot for this parser. Great job!

**Comment by lapinos03** [comment]
Your question has no sense. An option is there for passing an argument (`-m 222`) otherwise don't use it (and your `inodes` will stay with its default value).

**Comment by eike-fokken** [comment]
@InformatikerImAll
Maybe you could implement this option as a subcommand with a positional argument.
Problem is, the syntax must change then, because apparently subcommands may not start with "--".

**Comment by eike-fokken** [comment]
@lapinos03 
I think, what @InformatikerImAll wants is a flag, that is also an option, so it can have arguments but doesn't need them. And I think it is a valuable question, although I don't know, whether its possible with CLI11.

**Comment by eike-fokken** [comment]
Does

```C++
CLI::Option *m = app.add_option("-m, --mkfs", inodes, "Create Image: default is 1000 inodes.")->expected(0,1);
```

work?

**Comment by InformatikerImAll** [comment]
Hey @eike-fokken. I solved it already the same way you did and it works. I did not understand it at that time and was new to this. But thanks for the answer.

**Comment by henryiii** [comment]
Sorry for not seeing this earlier, yes, `->expected(0,1)` will make a "flag/option".
