### ISSUE TITLE
Help with unordered_set

### ISSUE THREAD

**Issue by dfleury2** [CLIUtils/CLI11#558]
Hi,
I have seen some tests against unordered_set, but this simple example does not work.
Do you see what I am doing wrong ?
Regards,

launched using : ./bin/unordered_set -v 1 -v 2 -v 3 -v 4
got : -v: At Most 1 required but received 4

using ->expected(1, 10); display nothing but no error.

```
#include <CLI/CLI.hpp>

#include <iostream>
#include <unordered_set>
#include <vector>

int main(int argc, char **argv)
{
    CLI::App app;

    std::vector<int> v_integers;
    app.add_option("-v", v_integers, "Some values");

    std::unordered_set<int> s_integers;
    app.add_option("-s", s_integers, "Some values");

    CLI11_PARSE(app, argc, argv);

    for (const auto& i : v_integers) std::cout << "v: " << i << " ";
    std::cout << std::endl;
    for (const auto& i : s_integers) std::cout << "s: " << i << " ";
    std::cout << std::endl;
}

```

Edit:
Something did not work as I expected, when I use vector or unordered set...
./bin/unordered_set -v 1 -v 2 -v 3 -v 4 -s 2
-> do no display s values, onyl the v values
./bin/unordered_set -v 1 -v 2 -v 3 -v 4 -s 2 -s 3
-> -s: At Most 1 required but received 2

**Comment by jzakrzewski** [comment]
Your code does not define "-v".

**Comment by dfleury2** [comment]
oh, yes sorry, I change the sample, I have made lot of tries.

**Comment by dfleury2** [comment]
I gave up on the lexical_converstion, and all the enable_if.
I use simply :
```
    std::unordered_set<int> s_integers;
    app.add_option_function<std::vector<std::string>>("-s", [&s_integers](auto&& strings) {
        for (const auto& s : strings) {
            s_integers.insert(std::stoi(s));
        }
        }, "Some integers");
```
