### ISSUE TITLE
Compile Error by use with boost.locale

### ISSUE THREAD

**Issue by opelx** [CLIUtils/CLI11#562]
Hi,

I've here a strange compile error if I use boost.locale to translate the help string. The problem rise here by upgrading CLI11 from v1.6.1 to 1.9.1. Anyway, the error is e.g.

[code]
init.cpp:123:13: error: no matching member function for call to 'add_flag'
        app.add_flag("-q,--quiet",
        ~~~~^~~~~~~~
CLI_191/CLI/App.hpp:830:13: note: candidate function [with T = boost::locale::basic_message<char>, $1 = 0] not viable: expects an l-value for 2nd argument
    Option *add_flag(std::string flag_name,
            ^
CLI_191/CLI/App.hpp:893:13: note: candidate function not viable: no known conversion from 'basic_message<char>' to 'std::function<void (std::int64_t)>' (aka 'function<void (long)>') for 2nd argument
    Option *add_flag(std::string flag_name,
            ^
CLI_191/CLI/App.hpp:798:13: note: candidate template ignored: requirement 'std::is_const<boost::locale::basic_message<char>>::value' was not satisfied [with T = boost::locale::basic_message<char>]
    Option *add_flag(std::string flag_name, T &flag_description) {
            ^
CLI_191/CLI/App.hpp:807:13: note: candidate template ignored: requirement 'std::is_constructible<boost::locale::basic_message<char>, long>::value' was not satisfied [with T = boost::locale::basic_message<char>]
    Option *add_flag(std::string flag_name,
            ^
CLI_191/CLI/App.hpp:844:13: note: candidate template ignored: could not match 'vector' against 'basic_message'
    Option *add_flag(std::string flag_name,
            ^
CLI_191/CLI/App.hpp:790:13: note: candidate function not viable: requires single argument 'flag_name', but 2 arguments were provided
    Option *add_flag(std::string flag_name) { return _add_flag_internal(flag_name, CLI::callback_t(), std::string{}); }
[/code]

The line of confusion is simply

`        app.add_flag("--build-info",
            boost::locale::translate("Show build informations."));`

using `boost::locale::gettext` suffers from the same problem. 

The documentation of the relevant boost functions is [here](https://www.boost.org/doc/libs/1_73_0/libs/locale/doc/html/group__message.html).

The interesting part is, there are no errors by use of `add_option`:

[code]
        app.add_option("files", cli_parameter.files,
               translate("One or more file(s)."))
            ->required()
            ->check(CLI::ExistingFile);
[/code]

compiles fine!
So how can it be fixed, even supporting i10n? 

Thanks

**Comment by henryiii** [comment]
You are giving the string to the output variable instead of the help string. Either add a bool for the output, or set the help string after the constructor.

**Comment by phlptp** [comment]
I believe you could cast it to const as well, but adding a bool might be the most straightforward even if you don't use the bool.

**Comment by opelx** [comment]
Thanks for answers, but isn't the syntax the pure flags one shown at [docs](https://cliutils.github.io/CLI11/book/chapters/flags.html)?

What has been changed since v1.6.1?

**Comment by phlptp** [comment]
For the pure flags, the second argument must be `const` and must be convertible to `std::string`  

Maybe should add that requirement to the documentation.

**Comment by phlptp** [comment]
To address your second question what has changed is that a much wider range of types is supported for use in flags, so instead of just a few specific types being able to be used in flags, you can use just about any type can be used as long as there is some path to convert from a string,  I think the lack of const in your case from the output probably is the issue, so it was trying to figure out a way to assign to the return object.

**Comment by opelx** [comment]
Thanks. After digging deeper, there is a const problem with boost's translate() in relation to expected value by CLI add_flag. 
Adding a dummy bool seems to solve this issue. Is it safe to use one dummy bool for all flags affected?

**Comment by phlptp** [comment]
There should be no memory or race issues with using the same variable.

The result you actually get out could be inconsistent, but if you are not using it, it probably doesn't matter too much.

**Comment by opelx** [comment]
Thanks!

**Comment by henryiii** [comment]
Please consider:

```cpp
app.add_flag("--build-info")->description(boost::locale::translate("Show build informations."));
```

This is clearer IMO and does not have issues with being interpreted incorrectly.
