### ISSUE TITLE
error: ‘class CLI::App’ has no member named ‘set_version_flag’

### ISSUE THREAD

**Issue by xiaou** [CLIUtils/CLI11#567]
error: ‘class CLI::App’ has no member named ‘set_version_flag’

I have got the  most recent release v1.9.1.

**Comment by jzakrzewski** [comment]
The related PR #452 is for the 2.0 Milestone. So you won't have that in v1.9.1.

**Comment by henryiii** [comment]
Yes, due to the birth of my daughter, 2.0 is delayed. master is quite safe for now if you want to live at HEAD.

**Comment by phlptp** [comment]
2,0 is released now so this should be in a tagged version
