### ISSUE TITLE
default value for flag is not shown in help

### ISSUE THREAD

**Issue by pwm1234-sri** [CLIUtils/CLI11#569]
The default value for a flag is not shown in the help string. 

For example I have a flag ``--alignment`` with a negate flag ``--no-alignment`` and the help output is:

```
  --alignment,--no-alignment{false}
                              Do Alignment Processing
```

But there is nothing that shows the default value.

**Comment by phlptp** [comment]
Could you clarify what you would be expecting.  
Flags are true by default.  and 
```
--alignment,--no-alignment{false}
                              Do Alignment Processing
```
clearly shows a difference between `--alignment` and `--no-alignment`  so I am unclear what is expected?

**Comment by pwm1234-sri** [comment]
But there is nothing saying that ``--alignment`` is the default value. A user has to know that. And what if for some strange but justified reason the default is false? I believe what I am looking for is some indication of the chosen default value. Perhaps
``[default=true]`` (or ``[default=false]``.

**Comment by phlptp** [comment]
--alignment isn't a default value.  If the flag `--alignment` is given on the command line. it will pass a value equivalent to "true",  1, or something similar to the callback or value assignment given when the flag was created.  What this value is is context dependent which the help generation doesn't really have.  

if you specify `->default_val(true)`  that is a default value which  can be used if no argument is given

the argument in the braces on the flag name specification defines what gets passed as a value if no other value is specified.  You can make it show in the help  via.
```
--alignment{true},--no-alignment{false}
```

but unless it is specified by the user there is no way the help generation can generate some string there that will make sense in all cases, so far better to not include that unless the user specifies.  

I am looking into how a default value is displayed in help.  There may be something to make that a little clearer particularly for flags.

**Comment by pwm1234-sri** [comment]
You said "if you specify ->default_val(true) that is a default value which can be used if no argument is given" - that default value is what I think should be indicated in the help. Thanks for your effort on CLI11.
