### ISSUE TITLE
Support overriding arguments

### ISSUE THREAD

**Issue by richard-viney** [CLIUtils/CLI11#58]
Hi, thanks for the great library!

Is it possible to specify arguments multiple times and have the last one take precedence?

E.g. `my-app --name foo --name bar` would be identical to `my-app --name bar`.

I know there is good support for array arguments, but using them to get the above functionality doesn't seem ideal.

Thoughts?

**Comment by henryiii** [comment]
It's coming out in 1.3. See #39 and #38. Also #48.  Seems like that was a really good suggestion, @lambdafu ! It's called `take_last`and can even be set on the default argument for your app.

**Comment by richard-viney** [comment]
Sounds great, looking forward to the release :-)

**Comment by henryiii** [comment]
I might change the default to `take_last(true)` before the release, since it seems that other common programs like git use it.

**Comment by henryiii** [comment]
1.3 is released, and this is now possible.
