### ISSUE TITLE
Group name "Hidden" shows up in help

### ISSUE THREAD

**Issue by lczech** [CLIUtils/CLI11#589]
According to https://cliutils.github.io/CLI11/book/chapters/options.html, the group name "Hidden" should lead to the options in that group not being shown in the help. However, with CLI11 v1.9.1, they still show up. I think that the CLI11 book should be updated accordingly, and instead mention that an empty group name will lead to the desired outcome.

**Comment by henryiii** [comment]
The book is a bit out of date, sadly - better than when it was in a different repo, but still a bit behind. Happy to take PRs. I think that `""` is the hidden group.

**Comment by phlptp** [comment]
@henryiii   how do I update the book on github pages?

**Comment by henryiii** [comment]
Oops. Don't think I ever reimplemented that in GHA. Should be really easy now (https://learn.scientific-python.org/development/guides/gha-basic/#github-pages) - I'll try to do that soon-ish.

**Comment by henryiii** [comment]
Done in #897 & now live.
