### ISSUE TITLE
App::parse() and quote-enclosed executable paths containing spaces

### ISSUE THREAD

**Issue by fkutzner** [CLIUtils/CLI11#591]
Hi,

`App::parse(arguments, true)` currently fails if the executable's path contains spaces. Its [API documentation](https://cliutils.github.io/CLI11/class_c_l_i_1_1_app.html#a187f08c5326d89319802162e33faff4e) doesn't mention whitespace handling. Enclosing in quotes doesn't help:

```
#include "CLI/CLI.hpp"

int main(int argc, char** argv) {
  CLI::App app1("app");
  app1.add_flag("--foo");

  try {
    // fails
    app1.parse("\"Foo Bar\" --foo", true);
  }
  catch (CLI::ParseError const& e) {
    app1.exit(e);
  }

  return 0;
}
```

Tested with commit 4af78bee (2021-04-05), this produces:

```
The following argument was not expected: Bar"
Run with --help for more information.
```

Unfortunately, narrow strings aren't usually UTF8-encoded on Windows, so it is not possible to simply use `argv` instead.

**Edit:** removed note about older version of the example

**Comment by phlptp** [comment]
@henryiii Going to try to fix this one yet then that will probably be the last one in this burst of fixes.

**Comment by Chronial** [comment]
Thanks a lot for the fix. In case anybody else is also stuck on an old version, here is a workaround. `WToU8` is any function that converts a wstring into an utf8 string.
``` cpp
int argCount = 0;
wchar_t** const parsedArgs = CommandLineToArgvW(GetCommandLineW(), &argCount);
std::vector<std::string> utf8Args;
for (int i = 0; i < argCount; i++) {
  utf8Args.push_back(WToU8(parsedArgs[i]));
}
LocalFree(parsedArgs);
std::vector<char const*> utf8Argv;
for (std::string const& s : utf8Args) {
  utf8Argv.push_back(s.c_str());
}

app.parse(argCount, utf8argv.data());
```

**Comment by henryiii** [comment]
Any reason you are stuck on an old (<2.0) version? Just curious.

**Comment by Chronial** [comment]
I was afraid you were going to ask that :). It has nothing to do with CLI11 itself – we are just currently having issues with our internal package management.
