### ISSUE TITLE
Creating options that are common between all sub commands

### ISSUE THREAD

**Issue by TomAtkinsonArm** [CLIUtils/CLI11#608]
Hi, I've attempted a few times to declare options and flags that are usable in the main context and sub commands but cant seem to get it working.

An awful example but this is my situation
```
Main Help

random command

Options:
 --width
 --height

Commands:
 do_something
```

```
do_something Help

more random commands

Options:
 --width
 --height
```

When I attempt to redeclare the width and height options I get an error stating that the option is already declared. I am yet to find an API usage which allows for the interoperability of options and flags with different sub commands

Any guidance on this would be great :)

Thanks,
Tom

**Comment by phlptp** [comment]
If you declare the options in the main app, and then set the subcommand to `.fallthrough()` it would allow the options to be used in both contexts.    I am not sure if that is what you are looking for or not.  

the other option is to create those options a standalone shared_ptr to a `CLI::App`   
```c++
double height;
double width;
// create a nameless app so it works as an option group
auto subap=std::make_shared<CLI::App>();
subap.add_option("--height", height);
subap.add_option("--width",width);

auto subc1=app.add_subcommand("subcom1);

subc1->add_subcommand(subap);

auto subc2=app.add_subcommand("subcom2);

subc2->add_subcommand(subap);

```

this should allow the options in both subcommands.  The parent for fallthough would be the second one however if that situation came up which could be confusing in some cases.  

I think in general the recommendation is to use fallthrough and declare the options in the main context if the options apply to multiple subcommands.

**Comment by TomAtkinsonArm** [comment]
Very quick response thank you!

Ill give `fallthrough()` a shot and get back to you if this solved my issue

**Comment by TomAtkinsonArm** [comment]
fallthrough() doesn't work for my specific setup. But creating option groups and defining the interoperability that way works great. Is there anyway to clean up the help menu when using lots of option groups? The default is a `[Option Group: Subcommands]` header for each group
