### ISSUE TITLE
default_str() option modifier doesn't appear to work

### ISSUE THREAD

**Issue by matthew-cacheq** [CLIUtils/CLI11#628]
Using the following code to create an option, setting the "default_str" always results in the option being an empty string when the option isn't supplied on the command line.

auto option_stub_output_path = app_options.add_option( "--os, --stub_output", stub_output_file_path );
option_stub_output_path->default_str( "." );

**Comment by phlptp** [comment]
That is by design.  The default_str is used in cases where no argument was supplied.  for example `app_options["--os"]->as<std::string>()`  would return ".";

it will not overwrite what is `stub_output_file_path`.  Doing so by default would cause a lot of issues.  
If you wish this behavior use the following.

```c++
auto option_stub_output_path = app_options.add_option( "--os, --stub_output", stub_output_file_path );
option_stub_output_path->default_str( "." )->run_callback_for_default();
```

**Comment by matthew-cacheq** [comment]
Yes, I would expect that when no argument was supplied to the --os option. But I also assumed that if the --os option wasn't even given on the command line, `stub_output_file_path` would also return a "." string. Is that not the case?

**Comment by phlptp** [comment]
if no argument is given the variable that is passed is not modified.  

unless the `run_callback_for_default()`  modifier is used.

**Comment by matthew-cacheq** [comment]
Where is that modifier documented? I didn't find it in any of the online doc.

**Comment by phlptp** [comment]
https://github.com/CLIUtils/CLI11#option-options

At least it is supposed to be.  Doesn't look like it is there.  I will make sure it gets added

**Comment by matthew-cacheq** [comment]
Any verbiage for `run_callback_for_default` does not appear anywhere on that page.

**Comment by phlptp** [comment]
https://cliutils.github.io/CLI11/book/chapters/options.html  In the customization section.  But this does appear to be an oversight that will get corrected soon.

**Comment by matthew-cacheq** [comment]
OK.In the meantime can you give me a quick snippet to do what I want?

**Comment by phlptp** [comment]
```
option_stub_output_path->default_str( "." )->run_callback_for_default();
```

**Comment by matthew-cacheq** [comment]
Thanks.
