### ISSUE TITLE
Validator ExistingFileOrDirectory

### ISSUE THREAD

**Issue by lczech** [CLIUtils/CLI11#63]
For a program that I am currently writing, it would be nice to have a validator that checks whether a path is existing. Kind of an `or` between `ExistingFile` and `ExistingDirectory`:

```cpp
/// Check for an existing file or directory
inline std::string ExistingFileOrDirectory(const std::string &filename) {
    struct stat buffer;
    bool exist = stat(filename.c_str(), &buffer) == 0;
    if(!exist) {
        return "Path does not exist: " + filename;
    }
    return std::string();
}
```

Could also be called `ExistingPath`, assuming that all kinds of files are allowed, e.g., block devices etc, see https://linux.die.net/man/2/stat

**Comment by henryiii** [comment]
Sure, that could be useful. Could you make a PR?

**Comment by henryiii** [comment]
Now Validators directly support  `&` and `|`, so `ExistingFile | ExistingDirectory` is also possible. But ExistingPath was still useful because it supports other things besides just files and directories. Plus the type is displayed as `PATH` while or-ing `FILE` and `DIR` just gives `TEXT`.
