### ISSUE TITLE
How to disable "Combined names" but keep "Separate names"

### ISSUE THREAD

**Issue by certik** [CLIUtils/CLI11#636]
We use CLI11 in [LFortran](https://gitlab.com/lfortran/lfortran/) and we just ran into the following problem. The following creates an executable `expr` out of the object files provided at the command line.
```
lfortran  expr.o -o expr
```
You can add one or more `-I` include options as follows:
```
lfortran -I/some/path1 -I/some/path2  expr.o -o expr
```
The `-I` option can be repeated. Unfortunately, if you include the `-I` option, then `expr.o` also gets parsed as an `-I` option due to the "Combined names" feature of [Containers of options](https://cliutils.github.io/CLI11/book/chapters/options.html). 

How do I make CLI11 accept multiple `-I` options as "Separate names", but not append any subsequent name as part of it?

Here is the relevant part of our code:
```
        std::vector<std::string> arg_I;
        std::vector<std::string> arg_files;
        app.add_option("files", arg_files, "Source files");
        app.add_option("-I", arg_I, "Include path");
```
In the above example, `expr.o` (and any other "loose" files) should be part of `arg_files`, and each `-I` option should be part of `arg_I`.

Here is the full code: https://gitlab.com/lfortran/lfortran/-/blob/fd498bf6b4076d7d0c640a8cf8dfa2db345da7c3/src/bin/lfortran.cpp#L1094

**Comment by henryiii** [comment]
You need `->allow_extra_args(false);`:

```cpp
        std::vector<std::string> arg_I;
        std::vector<std::string> arg_files;
        app.add_option("files", arg_files, "Source files");
        app.add_option("-I", arg_I, "Include path")->allow_extra_args(false);
```

This will enforce the "type size" (1 for normal vectors, 2 for vectors of complex numbers, etc) for each instance parsed.

**Comment by certik** [comment]
@henryiii thanks! I applied the following patch:
```diff
diff --git a/src/bin/lfortran.cpp b/src/bin/lfortran.cpp
index e63dbecdc..91af34f77 100644
--- a/src/bin/lfortran.cpp
+++ b/src/bin/lfortran.cpp
@@ -1102,7 +1102,7 @@ int main(int argc, char *argv[])
         app.add_flag("-E", arg_E, "Preprocess only; do not compile, assemble or link");
         app.add_option("-l", arg_l, "Link library option");
         app.add_option("-L", arg_L, "Library path option");
-        app.add_option("-I", arg_I, "Include path");
+        app.add_option("-I", arg_I, "Include path")->allow_extra_args(false);
         app.add_option("-J", arg_J, "Where to save mod files");
         app.add_flag("--version", arg_version, "Display compiler version information");
 
@@ -1161,6 +1161,10 @@ int main(int argc, char *argv[])
         app.require_subcommand(0, 1);
         CLI11_PARSE(app, argc, argv);
 
+        for (auto &a : arg_I) {
+            std::cout << "-I: " << a << std::endl;
+        }
+
         if (arg_version) {
             std::string version = LFORTRAN_VERSION;
             std::cout << "LFortran version: " << version << std::endl;
```
but it still parses it as "combined names":
```console
$ lfortran -I/some/path1 -I/some/path2  expr.o -o expr
-I: /some/path1
-I: /some/path2
-I: expr.o
$ lfortran -I/some/path1 xx -I/some/path2  expr.o -o expr
-I: /some/path1
-I: xx
-I: /some/path2
-I: expr.o
```
I do have an older version of CLI11, so I'll try with the latest version also.

**Comment by certik** [comment]
I upgraded CLI11 to 2.0 and now it works!  Thank you for the help.

The update forced me to apply the following patches for default values:
```diff
-        app.add_option("--backend", arg_backend, "Select a backend (llvm, cpp, x86)", true);
+        app.add_option("--backend", arg_backend, "Select a backend (llvm, cpp, x86)")->default_str(arg_backend);
```
Does that sound about right?

**Comment by henryiii** [comment]
The mysterious "true" was replaced with `->capture_default_str()`, using "true" here was deprecated in 1.9. You can also manually set the default string (as you've done), or you can also set the defaults on the app so that all created options end up with `capture_default_str` on by default.

This "true" was originally because I couldn't support an uninitialized value unless I had a compile time setting in the function call. That limitation was removed and now it can act like a normal option.

**Comment by certik** [comment]
The `capture_default_str()` is what I was looking for, thanks! I fixed it in:

https://gitlab.com/lfortran/lfortran/-/merge_requests/1269

I think everything works now. Thank you again @henryiii for all your help. The CLI11 library has been working perfectly for us. Has everything that we need.
