### ISSUE TITLE
Casting out-of-range int to enum (class) is UB

### ISSUE THREAD

**Issue by SX91** [CLIUtils/CLI11#69]
Undefined behavior or undefined value, actually. Is it really a good idea to allow parsing to enums by simply casting integers?

**Comment by henryiii** [comment]
Any ideas on a fix?

**Comment by SX91** [comment]
That can't be easily fixed without removal of casting num to enum. I've removed this functionality in my local project and made hard requirement on `operator<<` for enums (so enum should be parsable for automatic cast).
Anyway, casting num to enum is a bad idea anyway, so either this ^ or require user to pass num->enum convert function/lambda.

**Comment by henryiii** [comment]
Do you have a PR or a diff of the changes? That sounds reasonable.

Edit: I see what you mean; this was rewritten by a PR; `operator <<` wasn't originally used.

**Comment by henryiii** [comment]
Let me know if that didn't fix it!
