### ISSUE TITLE
C++20 concepts compatibility issue

### ISSUE THREAD

**Issue by MikePopoloski** [CLIUtils/CLI11#75]
Concepts are coming to C++20 and one of the changes included is making `requires` a keyword. Assuming no major revisions to that, CLI11 will have to be updated to rename conflicting methods.

There's no rush on fixing this; I'm using CLI11 in a local project that has -fconcepts turned on and have worked around it by #define-ing the method to a new name. This issue is mostly a heads up so you can start thinking about it.

**Comment by henryiii** [comment]
Any name suggestions? For `requires` and possibly `excludes` to match.

**Comment by MikePopoloski** [comment]
Hmm, depends(), linked(), grouped(), I'm not really sure. Sorry :)
