### ISSUE TITLE
"is required" displayed twice in case of required option is not found  

### ISSUE THREAD

**Issue by RecklessTodd** [CLIUtils/CLI11#76]
In method App::_parse : 
    RequiredError(opt->single_name() + " is required"); 

In class RequiredError : 
    RequiredError(std::string name) : RequiredError(name + " is required", ExitCodes::RequiredError)

It would make sense to remove the "is required" string from App::_parse method and let it in the RequiredError() class.

**Comment by henryiii** [comment]
Should be fixed, thanks!

**Comment by henryiii** [comment]
Fixed in the just-released 1.4.
