### ISSUE TITLE
"is required is required" is printed if a subcommand parameter is not provided

### ISSUE THREAD

**Issue by taihup** [CLIUtils/CLI11#81]
Hi guys, I have this undesired behaviour when I try to parse a subcommand option. If a subcommand parameter is needed and it is not provided then CLI11 throw two times the string message "is required" after the parameter_flag that is required.

Example:
The executable should be running in this way:
./executable subcommand --paramter_flag <some_input_directory>
So, if some run mistakenly:
./executable subcommand

the following error appears:
#--paramter_flag is required is require

Thanks in advance,

Taihú

**Comment by henryiii** [comment]
In version 1.3 or master? That looks like something that was fixed in master 18 days ago.

**Comment by taihup** [comment]
Thnaks for your quickly response, I am using the version 1.3. I will try master and I will let you know if the problem persists.

**Comment by henryiii** [comment]
Reopen if it's not fixed in master. 1.4 should be out pretty soon!

**Comment by henryiii** [comment]
Fixed in 1.4.
