### ISSUE TITLE
Options without separating space consume positional arguments

### ISSUE THREAD

**Issue by rokups** [CLIUtils/CLI11#90]
Consider this application:

```cpp
    std::vector<std::string> options;
    std::string foo, bar;
    CLI::App app{"Test"};
    app.add_option("-O", options);
    app.add_option("foo", foo)->required();
    app.add_option("bar", bar)->required();
    CLI11_PARSE(app, argc, argv);
```

Following fails: `./test -OTest param1 param2`
Error: `bar is required`

Following works: `./test -O Test param1 param2`

It should either warn that `-OTest` is not a proper option instead of consuming `param1` or accept `-OTest` with value `Test`.

**Comment by henryiii** [comment]
It was a logic error for the "rest" part of a short option; it would not consider that in the always eat one calculation. Thanks!

PS: I will also add a test for `--Opt=value` while I'm thinking about it, just in case.

**Comment by rokups** [comment]
Thank you for the swift fix! By the way lib is simply **awesome**. Cant say that enough. :smile:  :+1:
