### ISSUE TITLE
Combine config with CLI-passed subcommand?

### ISSUE THREAD

**Issue by q121q** [CLIUtils/CLI11#947]
Hi,

thanks for publishing this great library. I wonder if there's any example showing how to combine --config option with a subcommand's another option.

What I want to do can be illustrated in the following example

For example:
config.toml
option_a = 1
[subc]
option_b = 2

./bin --config config.toml --option_b = 3

EDIT: we want option_b to have value of 3 instead of 2.

If you have any examples or directions that will be very much appreciated.
Thank you.

**Comment by phlptp** [comment]
If I am understanding correctly you want option_b to be available without a subcommand, but also work with a subcommand in the config file?   

If that is the case then option_b should be added under and option_group,  this will make it triggered from the main app.  Then add an alias("subc")  to the option group, so it can work like a subcommand as well, which should make it work from the config file you listed.

**Comment by phlptp** [comment]
the command line will take precedence so the value of option_b will be 3 in your example

**Comment by q121q** [comment]
Hi Philip, thanks so much for the fast response.

I will try your suggested approach!

Regards.
