### ISSUE TITLE
Release 1.5

### ISSUE THREAD

**Issue by henryiii** [CLIUtils/CLI11#96]
If all goes well, release 1.5 should happen on Monday. #88 should be fixed (? no test yet), and #87 will be too tricky to implement properly by 1.5.

**Comment by SX91** [comment]
https://github.com/CLIUtils/CLI11/issues/69? num to enum casting the way it is now can cause UB and unpredictable failures if used unchecked.

**Comment by henryiii** [comment]
Released.
